/* ════════════════════════════════════════════════════════════
   Content Data (Part 2: grammar, quizzes, tasks, assessment …)
   ════════════════════════════════════════════════════════════ */

/* ─── GRAMMAR KIT – 14 topics ──────────────────────────────── */
SRDP.grammar = [
  { id: 'articles', title: 'Articles: a / an / the / (nothing)',
    intro: 'German has articles too, but English uses them differently. This is the single biggest error source for Austrian students.',
    pairs: [
      { wrong: 'The school is very important for young people.', right: 'School is very important for young people.', note: 'General concept → no article' },
      { wrong: 'I go to the school every day.', right: 'I go to school every day.', note: 'Institution used for its purpose → no article' },
      { wrong: 'The life is complicated.', right: 'Life is complicated.', note: 'Abstract concept → no article' },
      { wrong: 'She plays the football.', right: 'She plays football. (BUT: She plays the piano.)', note: 'Sports → no article; instruments → the' },
    ],
    rule: 'Use "the" when both you and the reader know which specific one. Use "a/an" when introducing something new. Use no article for abstract concepts, general plurals, sports, meals, and institutions (school, church, hospital).' },
  { id: 'prepositions', title: 'Prepositions',
    intro: "German and English prepositions rarely match 1:1. Don't translate them one by one; learn the English combinations as chunks.",
    pairs: [
      { wrong: 'I am good in English.', right: 'I am good at English.', note: 'good at – not "in"' },
      { wrong: 'I am interested for this topic.', right: 'I am interested in this topic.', note: 'interested in' },
      { wrong: 'It depends from the weather.', right: 'It depends on the weather.', note: 'depends on' },
      { wrong: 'We discussed about the problem.', right: 'We discussed the problem.', note: 'discuss is transitive – no preposition' },
      { wrong: 'In the one hand…', right: 'On the one hand…', note: 'on the one hand / on the other hand' },
    ],
    rule: 'Learn prepositions as fixed chunks, not word-by-word. When in doubt, check: "interested IN", "depend ON", "result IN/FROM", "consist OF", "insist ON".' },
  { id: 'falsefriends', title: 'False friends (falsche Freunde)',
    intro: 'Words that look like German words but mean something completely different.',
    table: [
      { word: 'become', youThink: 'bekommen (to get)', itMeans: 'werden (to turn into)', correct: 'get / receive' },
      { word: 'sensible', youThink: 'sensibel (sensitive)', itMeans: 'vernünftig (reasonable)', correct: 'sensitive' },
      { word: 'actually', youThink: 'aktuell (current)', itMeans: 'tatsächlich (in fact)', correct: 'currently / at the moment' },
      { word: 'eventually', youThink: 'eventuell (maybe)', itMeans: 'schließlich (in the end)', correct: 'possibly / perhaps' },
      { word: 'sympathetic', youThink: 'sympathisch (likeable)', itMeans: 'mitfühlend (compassionate)', correct: 'likeable / nice' },
      { word: 'handy', youThink: 'Handy (mobile phone)', itMeans: 'praktisch (useful)', correct: 'mobile phone / cell phone' },
      { word: 'gymnasium', youThink: 'Gymnasium (school type)', itMeans: 'Turnhalle (sports hall)', correct: 'grammar school / secondary school' },
      { word: 'chef', youThink: 'Chef (boss)', itMeans: 'Koch/Köchin (cook)', correct: 'boss / manager' },
      { word: 'fabric', youThink: 'Fabrik (factory)', itMeans: 'Stoff (cloth, material)', correct: 'factory / plant' },
    ] },
  { id: 'sincefore', title: 'Since vs. for',
    intro: 'German uses "seit" for both. English distinguishes between a point in time and a period of time.',
    pairs: [
      { wrong: 'I have been living here since five years.', right: 'I have been living here for five years.', note: 'Period of time → for' },
      { wrong: 'I have been living here for 2019.', right: 'I have been living here since 2019.', note: 'Point in time → since' },
      { wrong: 'I study English since I am six.', right: 'I have been studying English since I was six.', note: 'since requires present perfect + past simple' },
    ],
    rule: 'FOR + period (for three years, for a long time, for ages). SINCE + point in time (since 2019, since Monday, since I was young). Since always pairs with present perfect.' },
  { id: 'conditionals', title: 'Conditionals for B2 writing',
    intro: 'Conditionals are the quickest way to show range. Using only "If… will…" keeps you at B1.',
    pairs: [
      { wrong: 'If schools will ban phones, students will be angry.', right: 'If schools banned phones, students would be angry.', note: 'Hypothetical – use past + would' },
      { wrong: 'If I would have more time, I read more.', right: 'If I had more time, I would read more.', note: 'No "would" in the if-clause' },
      { wrong: "Unless you won't study, you'll fail.", right: "Unless you study, you'll fail.", note: 'Unless = if not – no negative needed' },
    ],
    rule: 'In formal argument writing, use the 2nd conditional (If + past simple, would + infinitive) for hypothetical situations. This immediately signals B2 range. Also use "were to" for more formal hypotheticals: "If the government were to act now…"' },
  { id: 'passive', title: 'The passive voice',
    intro: "The passive voice is expected in formal writing (reports, articles, e-mails). Many Austrian students avoid it – don't.",
    pairs: [
      { wrong: 'They collected the data through surveys.', right: 'The data was collected through surveys.', note: 'Passive removes agent – formal and concise' },
      { wrong: 'People have made some improvements.', right: 'Some improvements have been made.', note: 'Impersonal passive – typical in reports' },
      { wrong: 'Factories are producing too much waste.', right: 'Too much waste is being produced by factories.', note: 'Passive shifts focus to what matters' },
    ],
    rule: 'Use the passive when: (1) who did something is unknown or unimportant, (2) you want to sound objective (reports), (3) you want to vary your sentence structures. Always show you can use it – at least 2–3 times per text.' },
  { id: 'wordorder', title: 'Word order',
    intro: 'German word order is flexible; English word order is strict. Translating sentence structure from German is a classic giveaway.',
    pairs: [
      { wrong: 'Yesterday went my family to Salzburg.', right: 'Yesterday, my family went to Salzburg.', note: 'No verb-second rule in English – subject before verb' },
      { wrong: 'I like very much football.', right: 'I like football very much.', note: "Don't separate verb and object" },
      { wrong: 'I go every day to school.', right: 'I go to school every day.', note: 'Place before time' },
    ],
    rule: 'English follows Subject–Verb–Object, then manner–place–time ("She sang beautifully at the concert last night"). Adverbs of frequency (always, often, never) go before the main verb but after "be": "He is always late."' },
  { id: 'commas', title: 'Commas: German rules do not apply',
    intro: 'German requires a comma before every "dass". English does not, but Austrian students sprinkle commas everywhere anyway.',
    pairs: [
      { wrong: 'I think, that school uniforms are unnecessary.', right: 'I think that school uniforms are unnecessary.', note: 'Never a comma before "that"' },
      { wrong: 'She said, that she would help.', right: 'She said (that) she would help.', note: 'Reported speech – no comma' },
      { wrong: 'If we act now we can still change things.', right: 'If we act now, we can still change things.', note: 'DO use a comma after a fronted if-clause' },
    ],
    rule: 'No comma before "that". Use a comma: after an introductory clause ("However, …", "If we act now, …"), between items in a list, and before "but/and" joining two complete sentences. When in doubt, leave it out.' },
  { id: 'uncountable', title: 'Uncountable nouns',
    intro: '"Informations" does not exist. A small group of nouns is always singular in English, even though the German words have plurals.',
    pairs: [
      { wrong: 'The teacher gave us many informations.', right: 'The teacher gave us a lot of information.', note: 'information – never plural' },
      { wrong: 'He gave me some good advices.', right: 'He gave me some good advice. / a piece of advice', note: 'advice – uncountable' },
      { wrong: 'The news are depressing.', right: 'The news is depressing.', note: 'news + singular verb' },
    ],
    rule: 'Always singular: information, advice, news, homework, furniture, knowledge, research, evidence, progress, traffic, money. To count them: "a piece of advice", "three items of furniture".' },
  { id: 'makedo', title: 'Make vs. do',
    intro: 'German "machen" covers both. English splits the territory, and the combinations are fixed.',
    pairs: [
      { wrong: 'I did a mistake in the test.', right: 'I made a mistake in the test.', note: 'make a mistake' },
      { wrong: 'We have to make our homework.', right: 'We have to do our homework.', note: 'do homework' },
      { wrong: 'Scientists made research on this topic.', right: 'Scientists did research on this topic.', note: 'do research' },
    ],
    rule: 'MAKE = create or produce: make a decision, make progress, make an effort, make money, make a difference. DO = activity or work: do homework, do research, do your best, do damage. Learn them as chunks.' },
  { id: 'adjadv', title: 'Adjective vs. adverb',
    intro: 'German adjectives and adverbs often look the same ("gut"). English usually adds -ly. Forgetting it is an instant accuracy error.',
    pairs: [
      { wrong: 'He drives very careful.', right: 'He drives very carefully.', note: 'Modifying a verb → adverb' },
      { wrong: 'She speaks English very good.', right: 'She speaks English very well.', note: 'good → well' },
      { wrong: 'The team played surprisingly bad.', right: 'The team played surprisingly badly.', note: 'bad → badly' },
    ],
    rule: 'Adverbs describe verbs – add -ly (careful → carefully). good → well. Exception: after sense verbs (look, sound, feel, taste, seem) use the adjective: "This sounds good", "That seems fair".' },
  { id: 'ifwhen', title: 'If vs. when vs. whether',
    intro: 'German "wenn" covers all three. English makes you choose, and the choice changes the meaning.',
    pairs: [
      { wrong: 'When I won the lottery, I would travel the world.', right: 'If I won the lottery, I would travel the world.', note: 'Hypothetical → if' },
      { wrong: 'If I finish school next year, I will study in Vienna.', right: 'When I finish school next year, I will study in Vienna.', note: 'Certain to happen → when' },
      { wrong: "I don't know if or not he will come.", right: "I don't know whether or not he will come.", note: '"or not" → whether' },
    ],
    rule: 'WHEN = it will definitely happen ("When I turn 18…"). IF = it might happen ("If it rains…"). WHETHER = a choice between alternatives, required before "or not" and after prepositions.' },
  { id: 'untilby', title: 'Until vs. by',
    intro: 'German "bis" covers both; English separates deadlines from durations. The mistake shows up constantly in formal e-mails.',
    pairs: [
      { wrong: 'Please send me the information until Friday.', right: 'Please send me the information by Friday.', note: 'Deadline → by' },
      { wrong: 'I will stay in London by Sunday.', right: 'I will stay in London until Sunday.', note: 'Continuing state → until' },
      { wrong: 'The report must be handed in until 8 May.', right: 'The report must be handed in by 8 May.', note: 'Deadline → by' },
    ],
    rule: 'BY = a deadline – the action is completed at (or before) that point: "Reply by Friday." UNTIL = an action or state continues up to that point: "I will wait until Friday."' },
  { id: 'relatives', title: 'Relative pronouns: who / which / that / whose',
    intro: 'German "der/die/das" maps onto several English words, and the comma rules are different too.',
    pairs: [
      { wrong: 'The students which protested were right.', right: 'The students who protested were right.', note: 'People → who' },
      { wrong: 'The book who I read was brilliant.', right: 'The book which/that I read was brilliant.', note: 'Things → which/that' },
      { wrong: 'My best friend, that lives in Graz, is visiting.', right: 'My best friend, who lives in Graz, is visiting.', note: 'Never "that" after a comma' },
    ],
    rule: 'WHO = people, WHICH = things, THAT = both (but only without commas), WHOSE = possession ("the author whose article I read"). Using relative clauses well is one of the easiest ways to show B2 range.' },
];

/* ─── QUIZZES per text type ────────────────────────────────── */
SRDP.quizzes = {
  essay: [
    { q: 'Can you use personal anecdotes in an essay?', options: ['Yes, they make it more interesting', 'No – use general or hypothetical examples instead', 'Only in the introduction', 'Only in the conclusion'], correct: 1, explanation: 'Essays require generalisations, not personal stories. Use "Studies show…" or "Imagine a student who…" instead.' },
    { q: 'What are the four layers of a strong body paragraph?', options: ['Point → Explain → Evidence → Link/close', 'Hook → Story → Moral → Question', 'Opinion → Opinion → Opinion → Summary', 'Question → Answer → Question → Answer'], correct: 0, explanation: 'Topic sentence (Point) → Explain why/how → Evidence or example → Closing sentence that draws a consequence or links forward. See the "Paragraph writing" section.' },
    { q: 'An essay task says "argue for OR against". What should you do?', options: ['Write about both sides equally', 'Choose one clear position and defend it throughout', 'Write about both sides, then choose in the conclusion', "It's optional – you can do either"], correct: 1, explanation: '"Argue" means take a clear position. Unlike "discuss", you are not presenting both sides equally – you defend one view.' },
    { q: 'Your essay currently uses only simple sentences. What happens to your score?', options: ['Range score is capped at a low band even if all sentences are correct', 'Nothing – accuracy matters more than complexity', 'You get full marks for accuracy', 'Range is unaffected; only accuracy counts'], correct: 0, explanation: 'The assessment scale explicitly rewards structural range. Only simple, B1-level grammar keeps Range (and with it Accuracy) in the lower bands, no matter how correct it is.' },
    { q: 'Which of these works best as a formal essay conclusion?', options: ['"So yeah, that\'s basically it!"', '"To sum up, guys, this is a really big problem."', '"Taking these points into consideration, it is clear that…"', '"In conclusion, this is important."'], correct: 2, explanation: '"Taking these points into consideration" is a proper B2 conclusion linker that signals a considered close. The others are too informal ("guys", "yeah") or say nothing ("this is important").' },
    { q: 'How long should your Matura essay be?', options: ['Around 250 words', 'Around 400 words – 360 to 440 is safe', 'As long as possible', 'There is no word count for essays'], correct: 1, explanation: 'The essay is the long task: ~400 words. With the ±10% tolerance, anything between 360 and 440 words is fine.' },
    { q: 'Which opening is best for a formal essay introduction?', options: ['"When I was twelve, my parents bought me a smartphone."', '"Have you ever wondered why we spend so much of our lives online?"', '"This essay will now discuss the topic of social media."', '"OMG, social media is everywhere these days!"'], correct: 1, explanation: 'A rhetorical question or striking fact makes a strong, formal hook. Personal anecdotes (A) belong in blogs, announcing your essay (C) is weak style, and (D) is far too informal.' },
  ],
  article: [
    { q: 'What is the most important feature of an article title?', options: ['It must be exactly 5 words', 'It must summarise the whole text', "It must grab the reader's attention", 'It must include the topic keyword'], correct: 2, explanation: 'Article titles should be catchy: rhetorical questions, alliteration, bold statements, direct address. A boring title loses marks on Task Achievement.' },
    { q: 'Can you address the reader directly in an article?', options: ["Never – it's too informal", 'Yes – "you" is expected in many articles', 'Only in the conclusion', 'Only if the task says so'], correct: 1, explanation: 'Articles should engage readers. Using "you" is a key article feature that distinguishes it from a neutral report.' },
    { q: 'An article task says it\'s for a "school magazine for teenagers". What register do you use?', options: ['Very formal – like a business report', 'Semi-formal to informal – engaging and personal', "Formal – because it's published", "It doesn't matter for articles"], correct: 1, explanation: 'Always match register to audience. A school magazine for teenagers calls for a friendly, engaging, semi-formal or informal tone.' },
    { q: 'Which of these is an appropriate article conclusion?', options: ['"Taking everything into consideration, it is my belief that…"', '"The data clearly demonstrates that this phenomenon requires urgent action."', '"So next time you reach for your phone, ask yourself: is it really worth it?"', '"I would therefore recommend that you consider this issue carefully."'], correct: 2, explanation: 'Articles should leave the reader thinking with a question or personal call to action. The other options sound like report or formal-letter conclusions.' },
    { q: 'What is the key difference between an essay and an article?', schools: ['ahs'], options: ['Articles are always shorter', 'An essay makes the reader think; an article makes the reader feel', 'Essays have titles, articles do not', 'There is no real difference'], correct: 1, explanation: 'Essays are fact-based, formal and built on generalisations. Articles are personal, emotional and engaging – they connect with the reader.' },
    { q: 'The task says your article will appear in a serious national newspaper. What changes?', options: ['Nothing – articles are always informal', 'Use a more formal, measured register but keep it engaging', 'Turn it into a report with headings', 'Add emojis to connect with readers'], correct: 1, explanation: 'The publication context controls the register. A national newspaper needs semi-formal language, but the article still has to engage: keep the hook and the direct address where they fit.' },
  ],
  report: [
    { q: 'Which of the following does NOT belong in a report header?', options: ['Date', 'Dear Sir or Madam,', 'From:', 'Subject:'], correct: 1, explanation: '"Dear Sir or Madam" is a greeting used in e-mails/letters, not in reports. Reports have a header (Date, From, Subject) but no greeting.' },
    { q: 'Where is it acceptable to include personal opinion in a report?', options: ['In every paragraph', 'In the introduction only', 'In the recommendations / conclusion only', 'Nowhere – reports are entirely objective'], correct: 2, explanation: 'The body of a report presents objective findings. The conclusion/recommendations section is where you can use "I would suggest…" or "In my view, the best solution is…"' },
    { q: 'What language feature is especially important in report writing?', options: ['Rhetorical questions', 'Personal anecdotes', 'The passive voice', 'Exclamation marks'], correct: 2, explanation: 'The passive voice ("The data was collected…", "It has been established that…") creates the neutral, objective tone that reports require.' },
    { q: '"The food is disgusting and the prices are outrageous." What is wrong with this report sentence?', options: ["It's too short", 'It uses emotional, subjective language', "It doesn't have a section heading", 'It uses the wrong tense'], correct: 1, explanation: 'Reports require neutral, objective language. Replace with: "A significant proportion of respondents rated the food quality as poor, and 68% described prices as too high."' },
    { q: 'Your report task mentions a student survey, but you have no real data. What do you do?', options: ['Write "I do not have any data"', 'Invent realistic, plausible figures and present them professionally', 'Leave out the findings section', 'Copy numbers from the task prompt'], correct: 1, explanation: 'You are expected to invent plausible data: "72% of respondents stated that…". What is assessed is how professionally you present and analyse it.' },
    { q: 'What must every single section of a report have?', options: ['A rhetorical question', 'A statistic', 'A heading', 'A recommendation'], correct: 2, explanation: 'Headings are the report\'s defining visual feature. The examiner should recognise your text as a report at first glance.' },
  ],
  blog: [
    { q: "You're writing a blog COMMENT. What must your first sentence do?", options: ['State your opinion immediately', 'Reference the original blog post by name', 'Ask a rhetorical question', 'Introduce the topic generally'], correct: 1, explanation: 'Blog comments open by referring to the original post: "Hi [name], I came across your post on [topic] and…". Naming the post makes the reference clear.' },
    { q: 'Which of these is appropriate in a blog post but NOT in a report?', options: ['Complex sentences', 'B2 linking words', 'Personal anecdotes and contractions', 'Topic sentences'], correct: 2, explanation: "Blogs welcome personal voice: contractions (I've, don't), personal stories (\"When I tried this…\"), and informal language." },
    { q: 'A blog post conclusion should:', options: ['Use a formal summary like "Taking these points into consideration…"', 'Invite readers to comment and share their own experiences', 'End with statistics to support your argument', 'Present a balanced view of both sides'], correct: 1, explanation: 'Blog posts must invite interaction: "What do you think? Let me know in the comments!" This is a genre convention the examiner will look for.' },
    { q: 'Does a blog COMMENT need a title?', options: ['Yes, always', 'No – only blog posts have titles', 'Only if it is longer than 250 words', 'Yes, but only a short one'], correct: 1, explanation: 'Blog posts get a catchy title; comments do not. A comment starts by referencing the original post instead.' },
    { q: 'What belongs at the very top of a blog post?', options: ['To / From / Date / Subject', 'Dear readers,', 'Username and date/time', 'A table of contents'], correct: 2, explanation: 'A blog post starts with a username and date/time (e.g. "by max_adventures · 22 March, 19:34"), then the title. E-mail headers and greetings belong to other text types.' },
    { q: 'Which sentence fits the blog register best?', options: ['"It is widely acknowledged that travelling broadens the mind."', '"This report examines the benefits of travelling."', '"Honestly? Backpacking through Portugal changed how I see everything."', '"I am writing to express my dissatisfaction with my holiday."'], correct: 2, explanation: 'Blogs live on personal voice and informal tone. The other options belong to reports and complaint e-mails.' },
  ],
  email: [
    { q: 'You\'re writing to "Dear Mr Johnson,". Which sign-off do you use?', options: ['Yours faithfully,', 'Yours sincerely,', 'Kind regards,', 'Best wishes,'], correct: 1, explanation: 'When you address someone by name (Dear Mr Johnson), use Yours sincerely. Yours faithfully is for Dear Sir/Madam (name unknown).' },
    { q: 'In a formal e-mail of complaint, which phrase is most appropriate?', options: ['"I\'m really unhappy about what happened."', '"Your service was absolutely terrible."', '"I am writing to express my dissatisfaction with…"', '"You totally let me down."'], correct: 2, explanation: 'Formal complaint language is measured and professional, not emotional. "I am writing to express my dissatisfaction with…" is the standard B2 opener.' },
    { q: 'A student writes "Hi there," at the start of a letter to the editor. What is wrong?', options: ["It's too short", 'It\'s too informal – should be "Dear Sir or Madam," or "Dear Editor,"', "It should include the editor's name", 'Nothing is wrong with it'], correct: 1, explanation: 'Letters to the editor are formal. Use "Dear Sir or Madam," or "Dear Editor," – never informal greetings.' },
    { q: 'What must the FIRST sentence of a letter to the editor contain?', options: ['Your name and age', 'A rhetorical question', 'The article title, the publication and the date', 'Your strongest argument'], correct: 2, explanation: '"I am writing in response to the article entitled “…”, which appeared in [publication] on [date]." – a clear reference to the article you are responding to is the expected opening.' },
    { q: 'In an e-mail of enquiry, which question form is most formal?', options: ['"Is there accommodation?"', '"Tell me about the accommodation."', '"I would like to know whether accommodation is provided."', '"Accommodation??"'], correct: 2, explanation: 'Indirect questions ("I would like to know whether…", "Could you please tell me what…") are the polite, formal standard at B2.' },
    { q: 'What belongs in the first paragraph of an application e-mail?', options: ['Your salary expectations', 'The position you are applying for and where you saw the advertisement', 'A funny personal story', 'Your full CV'], correct: 1, explanation: '"I am writing to apply for the position of… as advertised in/on…" – position + source, in the very first sentence.' },
    { q: 'How many header elements does a formal e-mail need?', options: ['Two: To and Subject', 'Three: To, From, Date', 'Four: To, From, Date, Subject', 'None – just start with the greeting'], correct: 2, explanation: 'All four: To, From, Date, and a clear Subject line. Missing header elements cost Task Achievement points.' },
    { q: 'Your complaint demands action. Which closing is best?', options: ['"Fix this now or else!"', '"I would be grateful if you could rectify this matter and I look forward to your reply within 14 days."', '"Whatever you can do is fine, I guess."', '"Call me maybe."'], correct: 1, explanation: 'Firm but professional: a clear demand, a polite formula, and a deadline. Aggression and vagueness both lose marks.' },
  ],
  leaflet: [
    { q: 'What makes a leaflet look like a leaflet at first glance?', options: ['One long, unbroken block of text', 'A title plus short sections with subheadings', 'A To / From / Date / Subject header', 'A username and a date/time'], correct: 1, explanation: 'A leaflet is broken into short, scannable sections under clear subheadings. The layout itself signals the text type – an unbroken block of text reads like an essay instead.' },
    { q: 'What are the two main purposes of a leaflet?', options: ['To argue for one side and refute the other', 'To inform AND persuade a specific audience', 'To present survey data objectively', 'To confess a personal experience'], correct: 1, explanation: 'A leaflet informs the reader about something (an event, a service, a scheme) and persuades them to act on it. Weighing both sides belongs to other text types; neutral data is a report; personal confession is a blog.' },
    { q: 'Your leaflet is for a youth club aimed at teenagers. What register should you use?', options: ['Very formal, like a business e-mail', 'Neutral and impersonal, like a report', 'Accessible and direct, speaking straight to the reader', 'Academic, with phrases like "It is widely believed that…"'], correct: 2, explanation: 'Match register to audience. A youth club leaflet should be warm, direct and full of "you", while staying clean and readable – not slang. Formal or academic phrasing would feel wrong for that reader.' },
    { q: 'Which sentence works best as the ending of a leaflet?', options: ['"Taking these points into consideration, the event has clear benefits."', '"Come along on Saturday – bring a friend and see for yourself."', '"It is recommended that interested parties consider attendance."', '"In conclusion, this leaflet has described the event."'], correct: 1, explanation: 'A leaflet ends with a clear call to action that tells the reader exactly what to do next. The other options are report-style or over-formal closings and give the reader nothing to act on.' },
    { q: 'A leaflet for an event is nearly finished. What must not be missing?', options: ['A personal anecdote about the writer', 'The practical details – when, where and how to take part', 'A balanced discussion of pros and cons', 'A formal sign-off like "Yours faithfully"'], correct: 1, explanation: 'A leaflet has to let the reader act, so the date, time, place, price and contact matter as much as the call to action. Personal stories belong in a blog, weighing pros and cons in an essay, and a formal sign-off in a letter or e-mail.' },
    { q: 'How is a leaflet different from a report on the same event?', options: ['A leaflet uses headings; a report never does', 'A leaflet persuades and addresses the reader directly; a report stays neutral and objective', 'A leaflet is always longer than a report', 'There is no real difference between them'], correct: 1, explanation: 'Both can be well organised, but a report presents facts neutrally for someone who requested them, while a leaflet openly persuades a chosen audience and speaks to them directly with "you" and calls to action.' },
  ],
};

/* ─── FINAL MIXED QUIZ ─────────────────────────────────────── */
SRDP.finalQuiz = [
  { q: 'Which text type ALWAYS needs section headings?', options: ['Report', 'Article', 'E-mail', 'Blog post'], correct: 0, explanation: 'The report is the only text type with section headings. Headings in an e-mail or blog post would be a convention error.' },
  { q: 'The task says: "Write a blog comment (around 250 words)." Do you write a title?', options: ['Yes – every text needs a title', 'No – comments have no title; reference the original post instead', 'Only if you have space left', 'Yes, but in lower case'], correct: 1, explanation: 'Blog comments have no title. They open by referencing the post you are responding to.' },
  { q: 'How much time do you have for the whole Writing section (AHS, B2)?', schools: ['ahs'], options: ['90 minutes', '100 minutes', '120 minutes', '150 minutes'], correct: 2, explanation: '120 minutes for two tasks: roughly 65 minutes for the long task and 40 for the short one, leaving time to proofread both.' },
  { q: 'How much time do you have for the whole Writing section (BHS, B2)?', schools: ['bhs'], options: ['120 minutes', '150 minutes', '195 minutes', '240 minutes'], correct: 2, explanation: '195 minutes for three tasks of around 250 words each – roughly 55–60 minutes per task, planning and proofreading included.' },
  { q: 'Your 250-word task: which word count range is safe?', options: ['200–300', '225–275', '240–260', 'Anything over 250'], correct: 1, explanation: 'The tolerance is ±10%: for ~250 words that means 225–275. For ~400 words: 360–440.' },
  { q: '"Dear Sir or Madam," pairs with…', options: ['Yours faithfully,', 'Yours sincerely,', 'Best regards,', 'Cheers,'], correct: 0, explanation: 'Name unknown → faithfully. Name known (Dear Ms Brown) → sincerely.' },
  { q: 'Where may you give your personal opinion in a report?', options: ['Anywhere', 'In the findings section', 'In the conclusion/recommendations', 'Nowhere'], correct: 2, explanation: 'The body presents neutral findings; the final section may recommend and evaluate ("I would suggest…").' },
  { q: 'Which feature belongs in an article but NOT in a report?', options: ['Topic sentences', 'A title', 'Directly addressing the reader as "you"', 'Linking words'], correct: 2, explanation: 'Articles engage the reader directly; reports stay impersonal and neutral.' },
  { q: 'You copied a whole phrase from the task prompt into your text. Why is that a problem?', options: ["It isn't – the prompt is there to be used", 'Lifting from the prompt lowers your Range score', 'It only matters in formal texts', 'It makes the text too long'], correct: 1, explanation: 'Language "lifted" from the prompt does not count as your own production and damages the Lexical and Structural Range rating. Paraphrase instead.' },
  { q: 'The task operator is "discuss". What does that require?', options: ['Take one side and defend it', 'Look at the topic from different angles, weighing arguments for and against', 'Tell a personal story about the topic', 'Summarise an article'], correct: 1, explanation: '"Discuss" = both sides + weighing up. "Argue" = one clear position. Misreading the operator costs Task Achievement points.' },
  { q: 'You only manage to write about 2 of the 3 bullet points. What happens?', options: ['Nothing, two is enough', 'Task Achievement drops significantly – a full top score is impossible', 'You automatically fail the exam', 'Only Coherence suffers'], correct: 1, explanation: 'Each content point matters for Task Achievement. Missing one caps that criterion well below the top band. Plan your time so every bullet gets a paragraph.' },
  { q: 'Which sentence shows B2 structural range?', options: ['"School is important. Students learn a lot. Teachers help them."', '"Had the school introduced this policy earlier, fewer students would have struggled."', '"I think school is good and important and helpful."', '"School is very very important for all the people."'], correct: 1, explanation: 'Inversion plus a third conditional in one sentence: exactly the kind of structure that lifts your Range score. Strings of simple sentences keep you in the low bands.' },
  { q: 'Five minutes left, text finished. What is the single best use of the time?', options: ['Add another paragraph to be safe', 'Decorate the title', 'Count every word three times', 'Proofread for your personal top errors (articles, 3rd-person -s, tenses)'], correct: 3, explanation: 'Targeted proofreading catches the cheap accuracy errors that cost real points. Adding unplanned text usually creates new mistakes.' },
];

/* ─── TASK BANK (practice prompts) ─────────────────────────── */
SRDP.prompts = [
  { type: 'essay', length: 400, topic: 'Overtourism',
    scenario: 'Your class has discussed how tourism is changing European cities.',
    material: { kind: 'text', label: 'The statement you are discussing', source: 'From a European travel magazine',
      lines: ['"Tourism is eating its own children: the more successful a destination becomes, the less liveable it is for the people who call it home."'] },
    instruction: 'Write an essay (around 400 words) discussing this statement. Give your essay a title.',
    bullets: ['describe the economic benefits tourism brings to local communities', 'analyse the damage overtourism causes', 'suggest possible solutions and regulations'] },
  { type: 'essay', length: 400, topic: 'Social media and mental health',
    scenario: 'A youth organisation has invited students to submit essays for its annual publication.',
    material: { kind: 'text', label: 'The statement you are discussing', source: 'From a youth magazine',
      lines: ['"Social media has given teenagers a thousand new friends and taken away their peace of mind."'] },
    instruction: 'Write an essay (around 400 words) discussing this statement. Give your essay a title.',
    bullets: ['describe positive aspects of social media use', 'analyse negative effects on self-image and wellbeing', 'evaluate the responsibilities of platforms and parents'] },
  { type: 'essay', length: 400, topic: 'School uniforms',
    scenario: 'Your school is considering introducing a uniform and has asked students for written opinions.',
    material: { kind: 'text', label: 'The statement you are discussing', source: 'From a student newspaper',
      lines: ['"School uniforms do not create equality; they only hide inequality until the school bell rings."'] },
    instruction: 'Write an essay (around 400 words) arguing for or against mandatory school uniforms. Give your essay a title.',
    bullets: ['present arguments in favour of uniforms (equality, focus)', 'present arguments against them (expression, cost)', 'state and justify your own position'] },
  { type: 'essay', length: 400, topic: 'Voting at 16',
    scenario: 'An international student magazine is collecting essays on democracy and young people.',
    material: { kind: 'text', label: 'The statement you are discussing', source: 'Heard at a student debate',
      lines: ['"If you are old enough to pay taxes on your apprentice wage, you are old enough to vote on what happens with them."'] },
    instruction: 'Write an essay (around 400 words) discussing whether 16-year-olds should be allowed to vote in national elections. Give your essay a title.',
    bullets: ["explain why young people's voices matter in politics", 'discuss concerns about maturity and experience', "evaluate Austria's experience with voting at 16"] },
  { type: 'essay', length: 400, topic: 'Artificial intelligence in school',
    scenario: 'Your school\'s debating club is publishing essays about technology in education.',
    material: { kind: 'text', label: 'The statement you are discussing', source: 'From an education blog',
      lines: ['"A generation that lets AI do its homework will be the first that knows less than its parents."'] },
    instruction: 'Write an essay (around 400 words) discussing this statement. Give your essay a title.',
    bullets: ['describe how students currently use AI tools', 'analyse the risks for learning and fairness', 'suggest rules schools should introduce'] },
  { type: 'essay', length: 400, topic: 'Part-time jobs for teenagers',
    scenario: "A parents' association has asked for student perspectives on working while at school.",
    material: { kind: 'text', label: 'The statement you are discussing', source: "Overheard at a parents' evening",
      lines: ['"A Saturday job teaches a teenager more about real life than a whole year of school."'] },
    instruction: 'Write an essay (around 400 words) discussing whether teenagers should have part-time jobs. Give your essay a title.',
    bullets: ['describe the benefits of work experience', 'analyse possible negative effects on schoolwork', 'state your own conclusion with reasons'] },
  { type: 'article', length: 250, topic: 'A digital detox experience',
    scenario: 'Your school magazine is running a series on healthy technology habits and has asked for personal contributions.',
    instruction: 'Write an article (around 250 words) about a digital detox. Give your article a catchy title.',
    bullets: ['describe why you (or someone) decided to try it', 'explain what changed during the experience', 'tell readers what it taught you'] },
  { type: 'article', length: 400, topic: 'The future of work',
    scenario: 'An online magazine for young adults has invited contributions about working life.',
    instruction: 'Write an article (around 400 words) about how work is changing. Give your article a catchy title.',
    bullets: ['describe how remote work has changed daily life', 'discuss the benefits for employees', 'evaluate the challenges and what may be lost'] },
  { type: 'article', length: 250, topic: 'Volunteering',
    scenario: 'A community website wants to encourage more young volunteers.',
    instruction: 'Write an article (around 250 words) about volunteering. Give your article a catchy title.',
    bullets: ['explain why volunteering is worth trying', 'describe a typical experience volunteers can expect', 'convince readers to take the first step'] },
  { type: 'article', length: 400, topic: 'Travel that does not cost the earth',
    scenario: 'A European youth magazine is publishing a special issue on sustainable travel.',
    instruction: 'Write an article (around 400 words) about sustainable travel for young people. Give your article a catchy title.',
    bullets: ['describe why cheap weekend flights are problematic', 'present attractive alternatives (rail, local tourism)', 'give readers practical tips for their next trip'] },
  { type: 'report', length: 250, topic: 'School canteen food quality',
    scenario: 'The student council surveyed students about the school canteen. The principal has asked you to write up the results.',
    material: { kind: 'data', label: 'Survey results – 120 students, years 5–8',
      lines: ['58% buy lunch in the canteen at least three times a week', 'Food quality rated "poor" or "very poor" by 44%', '71% say healthy options sell out before the lunch break', 'Average waiting time: 14 minutes (the lunch break is 25)', '63% would pay up to €1 more for better quality'] },
    instruction: 'Write a report (around 250 words) for the principal based on these results.',
    bullets: ['present the main findings of the survey', 'analyse the impact on student health and concentration', 'recommend improvements'] },
  { type: 'report', length: 400, topic: 'Technology for learning',
    scenario: 'Your school wants to review how students use technology and has collected questionnaire data.',
    material: { kind: 'data', label: 'Questionnaire results – 210 students, years 4–8',
      lines: ['92% use a laptop or tablet for schoolwork every day', '47% say lessons rarely make use of digital materials', 'Most common uses: research (78%), vocabulary apps (54%), AI tools (49%)', '38% admit devices often distract them in class', 'Only 25% have ever been trained in checking online sources'] },
    instruction: 'Write a report (around 400 words) for the school management team based on these results.',
    bullets: ['present current usage patterns', 'analyse benefits and problems the data shows', 'recommend guidelines for future use'] },
  { type: 'report', length: 250, topic: 'Sports facilities',
    scenario: 'Your town council asked young residents about local sports facilities. You volunteered to summarise the answers.',
    material: { kind: 'data', label: 'Survey results – 85 residents aged 14–19',
      lines: ['66% use local sports facilities at least once a week', 'The skate park was rated "in poor condition" by 7 out of 10 users', 'Only 2 of the 6 outdoor pitches have working floodlights', '81% would use the sports hall more if there were evening slots'] },
    instruction: 'Write a report (around 250 words) for the town council based on these results.',
    bullets: ['present what young people think of the existing facilities', 'identify the main problems the data shows', 'suggest two realistic improvements'] },
  { type: 'report', length: 250, topic: 'School trip evaluation',
    scenario: "After this year's project week, students completed feedback forms. Your teacher asked you to write up the results.",
    material: { kind: 'data', label: 'Feedback results – 52 students, project week',
      lines: ['Overall rating: 3.1 out of 5', 'Best rated: outdoor activities (4.4 / 5)', 'Worst rated: accommodation (1.9 / 5) and food (2.2 / 5)', '60% found the daily programme "too full"', '88% would join another project week'] },
    instruction: 'Write a report (around 250 words) for your form teacher based on these results.',
    bullets: ['summarise how students rated the project week', 'present the most common criticisms', 'recommend changes for next year'] },
  { type: 'blog', length: 250, topic: 'Volunteering abroad',
    scenario: 'You write a personal blog about your experiences as a young Austrian. You have just returned from volunteering abroad.',
    instruction: 'Write a blog post (around 250 words) about the experience. Give your post a title.',
    bullets: ['explain why you decided to go', 'describe the challenges you faced', 'tell readers what the experience taught you'] },
  { type: 'blog', length: 400, topic: 'Living without a car',
    scenario: 'You blog about sustainable living. Your family gave up its car for a year.',
    instruction: 'Write a blog post (around 400 words) about the experience. Give your post a title.',
    bullets: ['describe how the experiment started', 'explain what was harder and easier than expected', 'invite readers to share their views'] },
  { type: 'blog', length: 250, topic: 'Comment: school start times',
    scenario: 'You follow a popular education blog and want to react to its latest post.',
    material: { kind: 'text', label: 'The blog post you are commenting on', source: 'jamie_teaches · "School should start at 10 a.m. – change my mind" · posted 2 days ago',
      lines: ['"Teenagers\' body clocks simply aren\'t made for 8 a.m. lessons. Research keeps telling us that adolescents need more sleep and perform better later in the day, yet schools keep dragging students out of bed at dawn. Start at 10, finish at 5, and everyone wins: better grades, better moods, fewer zombies in first period. Am I wrong?"'] },
    instruction: "Write a comment (around 250 words) responding to Jamie's post. Do not give your comment a title.",
    bullets: ['react to the original post', 'share your own experience with early school starts', 'state what you think schools should do'] },
  { type: 'blog', length: 250, topic: 'Comment: fast food ban near schools',
    scenario: 'A food blogger you follow has published a post that is getting a lot of reactions.',
    material: { kind: 'text', label: 'The blog post you are commenting on', source: 'lena.eats.well · "Keep burgers away from schools!" · posted yesterday',
      lines: ['"I\'m serious: fast food restaurants should be banned within 500 metres of every school. Walk past any school gate at lunchtime and you\'ll see queues of teenagers buying burgers, fries and energy drinks. We teach nutrition in biology and then let the burger chains undo it all at lunch. Distance rules work for casinos, so why not for junk food?"'] },
    instruction: "Write a comment (around 250 words) responding to Lena's post. Do not give your comment a title.",
    bullets: ["respond directly to the blogger's argument", 'describe what you observe at your own school', 'suggest a better (or stricter) solution'] },
  { type: 'email', length: 250, topic: 'Complaint: language course',
    scenario: 'You attended a two-week language course in Brighton that did not match what the website promised.',
    material: { kind: 'text', label: 'What the website promised', source: 'globalenglish.example – Summer Intensive Brighton',
      lines: ['"Small groups of maximum 10 students · all teachers fully qualified with at least five years\' experience · modern single rooms with private bathroom, five minutes from the school · full social programme included"'] },
    instruction: 'Write an e-mail (around 250 words) to the course provider.',
    bullets: ['compare what was promised with what you actually experienced', 'describe the problems with the accommodation', 'state what you want the company to do'] },
  { type: 'email', length: 250, topic: 'Letter to the editor: electric cars',
    scenario: 'You have read an article in an English-language newspaper and strongly disagree with it.',
    material: { kind: 'text', label: 'From the article you are responding to', source: '"The Electric Car Illusion" – The Daily Courier, 3 February 2026',
      lines: ['"Electric cars are a pointless trend that will change nothing. They are toys for wealthy city dwellers: too expensive for ordinary families, useless without charging stations, and powered by electricity that still comes from fossil fuels. Politicians who subsidise them are wasting taxpayers\' money."'] },
    instruction: 'Write a letter to the editor (around 250 words) responding to the article.',
    bullets: ["respond to the article's main claims", 'present your view on the environmental benefits', 'discuss the practical challenges of switching'] },
  { type: 'email', length: 250, topic: 'Application: summer internship',
    scenario: 'You have found an advertisement on the website of an international environmental NGO.',
    material: { kind: 'text', label: 'The advertisement', source: 'greenfuture.example – Summer Internship for School Students',
      lines: ['"We are looking for committed students (16+) to support our communications team for four weeks in July. Tasks include researching environmental topics, writing short texts for social media and helping at two public events. Good English, reliability and an interest in climate issues are essential. Apply by e-mail to Ms Hana Said, including your relevant experience and why you want to join us."'] },
    instruction: 'Write an e-mail of application (around 250 words) to Ms Said.',
    bullets: ['state which internship you are applying for and where you saw it', 'describe your relevant skills and experience', 'explain why you want to work for this organisation'] },
  { type: 'email', length: 250, topic: 'Enquiry: au pair agency',
    scenario: 'You are considering a gap year as an au pair in Ireland and found an agency online.',
    material: { kind: 'text', label: "From the agency's website", source: 'dublinaupairs.example – Your year in Ireland',
      lines: ['"We place au pairs aged 18–27 with carefully selected host families across Ireland. Programmes run from 6 to 12 months. Au pairs receive free board and lodging plus weekly pocket money. Language course options available. Contact us for details about requirements, fees and the application process."'] },
    instruction: 'Write an e-mail of enquiry (around 250 words) to the agency.',
    bullets: ['introduce yourself and your plans', 'ask about requirements and the application process', 'request information about costs and support'] },
  { type: 'email', length: 250, topic: 'Complaint: concert tickets',
    scenario: 'You bought a premium package for a concert online. The evening turned out very differently.',
    material: { kind: 'text', label: 'What you paid for', source: 'ticketnow.example – Premium Package (€189), Stadthalle Vienna',
      lines: ['"Guaranteed seating in rows 1–10 with a clear stage view · separate fast-lane entry · welcome drink and exclusive merchandise item · access to the VIP lounge after the show"'] },
    instruction: 'Write an e-mail (around 250 words) to the ticket company.',
    bullets: ['compare what you paid for with what you actually received', 'describe how the staff reacted on the evening', 'demand appropriate compensation'] },
  { type: 'email', length: 250, topic: 'Letter to the editor: city park',
    scenario: 'Your local English-language newspaper has reported on plans that affect young people in your district.',
    material: { kind: 'text', label: 'From the article you are responding to', source: '"Parking Garage to Replace Westpark" – Vienna Daily News, 14 March 2026',
      lines: ['"The city council confirmed on Thursday that Westpark will make way for a four-storey parking garage with 600 spaces. A spokesperson called the park \'underused green space\' and pointed to the chronic lack of parking in the district. Construction could begin as early as next spring."'] },
    instruction: 'Write a letter to the editor (around 250 words) about these plans.',
    bullets: ['refer to the newspaper report', 'explain what the park means to young people in your area', 'appeal to readers and the city council'] },
  { type: 'leaflet', length: 250, topic: 'School open day',
    scenario: 'Your school is holding an open day for pupils from local secondary schools and their parents. Your English teacher has asked you to write the text for the leaflet.',
    instruction: 'Write a leaflet (around 250 words). Give it a title and use meaningful subheadings.',
    bullets: ['explain what visitors can see and do on the day', 'describe what makes your school worth choosing', 'give the practical details and invite readers to come'] },
  { type: 'leaflet', length: 250, topic: 'A new recycling scheme',
    scenario: 'Your town is introducing kerbside recycling and the town office wants a leaflet for every household. You have offered to write the English version.',
    instruction: 'Write a leaflet (around 250 words) for local residents. Give it a title and use subheadings.',
    bullets: ['explain how the new scheme works', 'describe why it is worth taking part', 'tell readers how to sign up and where to get more information'] },
  { type: 'leaflet', length: 250, topic: 'A youth summer programme',
    scenario: 'A local youth centre is starting a summer programme and wants to attract teenagers from the area.',
    instruction: 'Write a leaflet (around 250 words) aimed at teenagers. Give it a catchy title and use subheadings.',
    bullets: ['describe the activities on offer', 'explain why teenagers should join', 'give the practical details (when, where, cost) and a clear call to action'] },
  { type: 'leaflet', length: 250, topic: 'Healthy eating at school',
    scenario: 'For a cross-curricular health project, your class is producing a leaflet to encourage students to eat more healthily at school.',
    instruction: 'Write a leaflet (around 250 words) for your fellow students. Give it a title and use subheadings.',
    bullets: ['explain why healthy eating matters for students', 'give practical, realistic tips for the school day', 'motivate readers to make one change this week'] },
  { type: 'email', length: 250, topic: 'Business enquiry to a supplier',
    scenario: 'During your practical training in a company\'s purchasing department, your supervisor asks you to contact an English-speaking supplier.',
    material: { kind: 'text', label: 'Your supervisor\'s note', source: 'Internal note',
      lines: ['"Please ask GreenPack Ltd for current prices for recycled packaging, minimum order quantities and delivery times to Austria. We need the goods by mid-October."'] },
    instruction: 'Write a formal e-mail of enquiry (around 250 words) to the supplier on behalf of your company.',
    bullets: ['introduce yourself and your company briefly', 'ask about prices, minimum order quantities and delivery times', 'state your deadline and ask for a prompt reply'] },
  { type: 'report', length: 250, topic: 'Guest / customer feedback',
    scenario: 'You work part-time at a hotel. Management surveyed guests and asked you to summarise the results in English for the international owners.',
    material: { kind: 'data', label: 'Guest survey – 140 guests, past season',
      lines: ['Overall satisfaction: 3.4 out of 5', 'Best rated: friendliness of staff (4.5) and breakfast (4.1)', 'Worst rated: Wi-Fi (2.1) and room cleanliness (2.6)', '61% would recommend the hotel to others', '48% found check-in too slow at peak times'] },
    instruction: 'Write a report (around 250 words) for the hotel owners based on these results.',
    bullets: ['summarise the main findings under clear section headings', 'analyse the strengths and the problem areas', 'recommend concrete improvements'] },
  { type: 'leaflet', length: 250, topic: 'A product launch (mini-company)',
    scenario: 'For your marketing project, your student mini-company is launching a reusable water bottle and needs a leaflet to hand out at a trade fair.',
    instruction: 'Write a lively, persuasive leaflet (around 250 words) for potential customers. Give it a catchy title and use subheadings.',
    bullets: ['introduce the product and what makes it special', 'explain the benefits for the customer and the environment', 'give the price, where to buy it, and a clear call to action'] },
  { type: 'email', length: 250, topic: 'Application answering a job ad',
    scenario: 'You have found an advertisement for a summer job that fits your BHS training.',
    material: { kind: 'text', label: 'The advertisement', source: 'alpinehotels.example – Summer Reception Assistant',
      lines: ['"We are looking for a reception assistant for July and August. Tasks: welcoming guests, answering e-mails and phone calls in German and English, simple bookings. We expect good English, a friendly manner and reliability. Apply by e-mail to Mr Berger with your relevant experience."'] },
    instruction: 'Write an e-mail of application (around 250 words) to Mr Berger. Keep the register formal throughout.',
    bullets: ['state which position you are applying for and where you saw it', 'describe your relevant skills, training and experience', 'explain why you are suitable and offer to attend an interview'] },
];

/* ─── LINKING WORDS ────────────────────────────────────────── */
SRDP.linkingWords = [
  { fn: 'Adding', basic: 'and, also', b2: 'Furthermore · Moreover · In addition · What is more · Not only… but also' },
  { fn: 'Contrasting', basic: 'but', b2: 'However · Nevertheless · On the other hand · Nonetheless · Although · Despite' },
  { fn: 'Cause', basic: 'because', b2: 'Since · As · Due to the fact that · Owing to' },
  { fn: 'Result', basic: 'so', b2: 'Therefore · Consequently · As a result · Thus · Hence' },
  { fn: 'Example', basic: 'like', b2: 'For instance · For example · Take for example · A case in point is' },
  { fn: 'Concession', basic: 'but', b2: 'Admittedly · Although · Even though · While · Despite the fact that' },
  { fn: 'Conclusion', basic: 'to finish', b2: 'To sum up · Taking everything into account · All things considered · On balance' },
];

/* ─── TASK OPERATORS ───────────────────────────────────────── */
SRDP.operators = [
  { op: 'discuss', what: 'Look at a topic from different angles. Present arguments for and against, weigh them up.', ex: 'There are strong arguments both for and against… On the one hand…' },
  { op: 'evaluate', what: 'Examine something and judge its quality or value. Is it good/bad, effective or not – and why?', ex: 'While this approach has certain merits, it fails to address…' },
  { op: 'argue (for/against)', what: 'Take a clear position and support it. Stronger than "discuss" – you are not neutral.', ex: 'I firmly believe that… The most convincing reason for this is…' },
  { op: 'analyse', what: 'Break something down into its parts or causes. How and why does it work (or not)?', ex: 'The main factors contributing to this are… A closer look reveals that…' },
  { op: 'compare', what: 'Point out similarities and differences between two or more things.', ex: 'While X tends to…, Y is more likely to… Both share…' },
  { op: 'describe', what: 'Give a clear picture of something – facts, features, what happened.', ex: 'The first thing visitors notice is… The programme consists of…' },
  { op: 'suggest / recommend', what: 'Propose ideas or solutions. What should be done?', ex: 'I would recommend that… One possible solution would be to…' },
  { op: 'explain', what: 'Make something clear. Say how or why something happens.', ex: 'The reason for this is that… This can be explained by the fact that…' },
];

/* ─── TEXT TYPE COMPARISON ─────────────────────────────────── */
SRDP.comparison = {
  head: ['Feature', 'Essay', 'Article', 'Report', 'Blog', 'E-Mail'],
  rows: [
    ['Contractions?', 'No', 'Depends', 'No', 'Yes', 'No'],
    ['Personal examples?', 'No', 'Yes', 'No', 'Yes', 'Depends'],
    ['Rhetorical questions?', 'Intro only', 'Yes, many', 'No', 'Yes', 'No'],
    ['Section headings?', 'No', 'No', 'Yes', 'No', 'No'],
    ['Recommendations?', 'No', 'Optional', 'Yes', 'Optional', 'Depends'],
    ['Address reader?', 'No', 'Yes', 'No', 'Yes', 'Yes'],
    ['Emotional language?', 'No', 'Yes', 'No', 'Yes', 'Measured'],
    ['Title?', 'Yes', 'Yes – catchy', 'Subject + headings', 'Post: yes / Comment: no', 'Subject line'],
  ],
};

/* ─── ASSESSMENT ───────────────────────────────────────────── */
SRDP.assessment = {
  criteria: [
    { name: 'Task Achievement', german: 'Erfüllung der Aufgabenstellung', desc: 'Did you do what the task asked?', detail: 'All content points covered with supporting detail; text type conventions followed; appropriate title/greeting/closing; word count within ±10%.' },
    { name: 'Coherence and Cohesion', german: 'Kohärenz und Kohäsion', desc: 'Does your text hold together logically?', detail: 'Clear overall structure; effective paragraphing; logical development; variety of linking devices; clear relationships between sentences.' },
    { name: 'Lexical and Structural Range', german: 'Spektrum sprachlicher Mittel', desc: 'How wide is your language?', detail: 'Variety of vocabulary and structures; complex sentence forms; not repeating the same phrases; appropriate register; not lifting from the prompt.' },
    { name: 'Lexical and Structural Accuracy', german: 'Sprachrichtigkeit', desc: 'How correct is your language?', detail: 'Grammar control; correct word choice; spelling; punctuation; accurate use of linking devices.' },
  ],
  bands: [
    { band: '10', label: 'Excellent', desc: 'Everything the task asks for, fully developed with well-chosen details. Conventions confidently used, wide range of vocabulary and complex structures, only occasional slips.' },
    { band: '8', label: 'Good', desc: 'All content points developed with relevant details. Clear structure, good range and variety, errors are rare and never cause misunderstanding.' },
    { band: '6', label: 'B2 minimum met', desc: 'This is the pass line of the official grid: all points developed but with limited supporting detail, a limited but appropriate set of linking devices, enough range including some complex forms, errors without damage to communication.' },
    { band: '4', label: 'Below B2', desc: 'Content points addressed but not developed, mostly simple linear sentences, repetition and lifting from the prompt, or errors pile up beyond simple structures.' },
    { band: '2', label: 'Far below B2', desc: 'Only parts of the task recognisable, very limited language, errors make parts of the text hard to understand.' },
    { band: '0', label: 'Not assessable / veto', desc: 'No assessable performance – or the text fails to address the set task (see the VETO rule above).' },
  ],
};

/* ─── CHECKLISTS ───────────────────────────────────────────── */
SRDP.checklists = {
  general: { label: 'General', items: [
    { id: 'task_read', text: 'Read the task twice – underlined text type, audience, word count, and all bullet points.', weight: 3 },
    { id: 'bullet_1', text: 'Bullet point 1 is addressed with a full paragraph of development.', weight: 3 },
    { id: 'bullet_2', text: 'Bullet point 2 is addressed with a full paragraph of development.', weight: 3 },
    { id: 'bullet_3', text: 'Bullet point 3 is addressed with a full paragraph of development.', weight: 3 },
    { id: 'word_count', text: 'Word count is within ±10% of the number the task states (for a 250-word task, 225–275).', weight: 2 },
    { id: 'topic_sents', text: 'Every body paragraph starts with a clear topic sentence.', weight: 2 },
    { id: 'linking', text: 'Used at least 5 different B2 linking words (Furthermore, However, Consequently…).', weight: 2 },
    { id: 'no_lifting', text: 'Did NOT copy words or phrases directly from the task prompt.', weight: 3 },
    { id: 'complex_gram', text: 'Used at least 2 complex structures (passive voice, conditional, relative clause).', weight: 2 },
    { id: 'proofread', text: 'Proofread for personal weaknesses (articles, third-person -s, tenses).', weight: 2 },
  ]},
  essay: { label: 'Essay', items: [
    { id: 'e_title', text: 'Wrote a clear, relevant title.', weight: 2 },
    { id: 'e_opinion', text: 'Opinion clearly stated in the introduction.', weight: 2 },
    { id: 'e_formal', text: 'Formal register throughout – no contractions, no slang.', weight: 2 },
    { id: 'e_no_personal', text: 'Avoided personal anecdotes – used general/hypothetical examples.', weight: 2 },
    { id: 'e_conclusion', text: 'Conclusion restates opinion in different words (not copied from intro).', weight: 1 },
  ]},
  article: { label: 'Article', items: [
    { id: 'a_title', text: 'Title is catchy – rhetorical question, alliteration, or bold statement.', weight: 2 },
    { id: 'a_audience', text: 'Wrote with a clear target audience in mind and matched register.', weight: 2 },
    { id: 'a_engage', text: 'Used at least one rhetorical question to engage the reader.', weight: 1 },
    { id: 'a_personal', text: 'Included at least one personal example or anecdote.', weight: 1 },
    { id: 'a_conclusion', text: 'Conclusion leaves the reader thinking or calls them to action.', weight: 1 },
  ]},
  report: { label: 'Report', items: [
    { id: 'r_header', text: 'Header includes Date, From, and Subject.', weight: 3 },
    { id: 'r_headings', text: 'Every section has a clear heading.', weight: 3 },
    { id: 'r_objective', text: 'Used objective, neutral language – no "I think" or emotional words in the body.', weight: 2 },
    { id: 'r_data', text: 'Included specific data / statistics when presenting findings.', weight: 2 },
    { id: 'r_recs', text: 'Conclusion includes clear, formal recommendations.', weight: 2 },
    { id: 'r_no_greeting', text: "Did NOT include a greeting (Dear Sir/Madam) – reports don't have one.", weight: 2 },
  ]},
  blog: { label: 'Blog', items: [
    { id: 'b_username', text: 'Included username and date/time at the top.', weight: 2 },
    { id: 'b_title', text: 'Blog post: wrote attention-grabbing title. Blog comment: no title needed.', weight: 2 },
    { id: 'b_personal', text: 'Wrote in a personal, informal voice with a distinct personality.', weight: 2 },
    { id: 'b_ref', text: 'Blog comment ONLY: opening sentence refers to the original post, ideally by name.', weight: 3 },
    { id: 'b_invite', text: 'Blog post: conclusion invites readers to comment.', weight: 2 },
  ]},
  email: { label: 'E-Mail', items: [
    { id: 'em_header', text: 'Header includes To, From, Date, and Subject line.', weight: 3 },
    { id: 'em_greeting', text: 'Used a formal greeting (Dear Sir or Madam, / Dear Mr/Ms [Name],).', weight: 2 },
    { id: 'em_purpose', text: 'First sentence states clearly why I am writing.', weight: 2 },
    { id: 'em_signoff', text: 'Correct sign-off: Yours faithfully (name unknown) / Yours sincerely (name known).', weight: 2 },
    { id: 'em_no_contr', text: 'No contractions used (wrote "do not" not "don\'t").', weight: 2 },
    { id: 'em_subtype', text: 'Followed conventions for sub-type (complaint / application / letter to editor / enquiry).', weight: 2 },
  ]},
  leaflet: { label: 'Leaflet', items: [
    { id: 'l_title', text: 'Gave the leaflet a clear title and broke the text into short sections with subheadings.', weight: 3 },
    { id: 'l_audience', text: 'Wrote for a specific audience and matched the register (accessible, not slang, not stiff).', weight: 2 },
    { id: 'l_persuade', text: 'Sold the benefits and addressed the reader directly with "you" – not a neutral report.', weight: 2 },
    { id: 'l_scannable', text: 'Kept sections short and scannable – no long, unbroken blocks of text.', weight: 2 },
    { id: 'l_cta', text: 'Ended with a clear call to action (come, sign up, get in touch).', weight: 3 },
    { id: 'l_details', text: 'Included the practical details the reader needs to act: date/time and place for an event, or how to sign up / where to buy / a website for a scheme or product.', weight: 2 },
  ]},
};

/* ─── PARAGRAPH WRITING ────────────────────────────────────── */
SRDP.paragraphs = {
  layers: [
    { key: 'point', num: '①', label: 'TOPIC SENTENCE', desc: 'States the point of this paragraph in one clear sentence. Everything else must connect back to it.' },
    { key: 'explain', num: '②', label: 'SUPPORTING SENTENCE', desc: 'Explains WHY or HOW your point is true. Build the logic: what is the mechanism?' },
    { key: 'evidence', num: '③', label: 'EVIDENCE / EXAMPLE', desc: 'Proves it with a concrete fact, statistic, or scenario. Names, numbers, places.' },
    { key: 'closing', num: '④', label: 'CLOSING SENTENCE', desc: 'Draws a consequence or links to the next paragraph. Never just repeat the topic sentence.' },
  ],
  formulas: [
    { label: 'CLAIM', formula: '[Topic] + [strong verb/adjective] + [your position]', example: '"The most significant problem with social media is its effect on young people\'s self-esteem."' },
    { label: 'CONTRAST', formula: 'While many believe that [X], the evidence suggests [Y].', example: '"While many believe that homework improves performance, the evidence suggests otherwise."' },
    { label: 'CAUSE', formula: 'One of the main reasons for [X] is [Y].', example: '"One of the main reasons for youth unemployment is the mismatch between education and the job market."' },
  ],
  tsMistakes: [
    { w: '"There are many problems."', fix: 'Too vague – which problems? Name them.' },
    { w: '"Technology has changed the world."', fix: 'Too broad – narrow it to your specific argument.' },
    { w: '"Is social media bad?"', fix: 'A question, not a claim. Make a statement.' },
  ],
  supports: [
    { label: 'EXPLANATION', sub: 'Answer "why?"', ex: '"This is largely because teenagers compare themselves to carefully edited images, which creates unrealistic expectations."' },
    { label: 'EVIDENCE', sub: 'Use data or facts', ex: '"A 2017 report by the Royal Society for Public Health ranked Instagram the worst platform for the mental health of 14- to 24-year-olds."' },
    { label: 'ILLUSTRATION', sub: 'Paint a scenario', ex: '"Consider a typical teenager who spends two hours a day scrolling – by the end of the week, they will have been exposed to hundreds of idealised images."' },
  ],
  anatomyExample: [
    { role: 'point', text: "Social media can be very harmful to teenagers' mental health." },
    { role: 'explain', text: 'Apps like Instagram and TikTok are full of edited photos and perfect-looking lives. When young people see this every day, they start to believe that their own lives are not good enough, which makes them feel unhappy and insecure.' },
    { role: 'evidence', text: "A 2017 report by the Royal Society for Public Health ranked Instagram as the most harmful social media platform for young people's mental health and body image." },
    { role: 'closing', text: 'If platforms do not do more to protect young users, these problems will only get worse in the future.' },
  ],
  closings: {
    strong: [
      { t: 'Draw a consequence', e: '"Schools must act before the problem gets worse."' },
      { t: 'Link forward', e: '"The economic impact is only part of the picture."' },
      { t: 'Reinforce the point', e: '"The cost of fast fashion can no longer be ignored."' },
    ],
    weak: [
      { w: '"So, as I said, social media is bad for self-esteem."', r: 'Just repeats the topic sentence' },
      { w: '"Also, the government should invest more in education."', r: "Introduces a new idea – that's the next paragraph" },
      { w: '"…and that is why this is an important topic."', r: 'Vague filler – says nothing' },
    ],
  },
  warmups: [
    { id: 'uniforms', title: 'Warm-up 1: School Uniforms',
      supporting: 'Many students say that their clothes are a way to show who they are, and wearing the same outfit every day would take that away from them.',
      evidence: 'In countries like the UK and Japan, where uniforms are common, students often report feeling pressure to express their individuality in other ways, such as through hairstyles or accessories.',
      closing: 'For teenagers, the freedom to choose what to wear is about more than fashion – it is about developing a sense of identity.',
      modelSentences: [
        { text: "One of the strongest arguments against school uniforms is that they limit students' ability to express themselves.", type: 'CLAIM' },
        { text: 'While uniforms may create a sense of equality, they also take away an important form of self-expression for young people.', type: 'CONTRAST' },
        { text: 'The biggest problem with school uniforms is that they ignore the role clothing plays in teenage identity.', type: 'CLAIM' },
        { text: 'Although supporters of uniforms focus on discipline, they often overlook how important personal style is for teenagers.', type: 'CONTRAST' },
        { text: 'Forcing students to wear the same clothes every day sends the message that individuality does not matter.', type: 'CAUSE' },
      ] },
    { id: 'smartphones', title: 'Warm-up 2: Smartphones in School',
      supporting: 'When a phone buzzes during a lesson, most students will look at it immediately, even if they know they should not. This interrupts not only their own learning but also the concentration of everyone around them.',
      evidence: 'A study from the University of Texas found that students who had their phones on their desk – even turned off – performed worse on tests than those whose phones were in another room.',
      closing: 'Unless schools find a way to deal with this distraction, students will continue to lose valuable learning time every single day.',
      modelSentences: [
        { text: "Smartphones are one of the biggest distractions in today's classrooms.", type: 'CLAIM' },
        { text: 'Even when students try to focus, the presence of a smartphone makes it much harder to concentrate on the lesson.', type: 'CLAIM' },
        { text: 'While phones can be useful learning tools, their negative effect on concentration in the classroom is hard to deny.', type: 'CONTRAST' },
        { text: 'The main reason why many teachers want to ban phones is that they constantly interrupt the learning process.', type: 'CAUSE' },
        { text: 'Although most students believe they can multitask, research shows that phones seriously reduce their ability to focus.', type: 'CONTRAST' },
      ] },
    { id: 'fastfood', title: 'Warm-up 3: Fast Food & Health',
      supporting: 'A typical fast food meal contains more calories, fat, and sugar than what a teenager needs for an entire day. Eating this regularly makes it very difficult to maintain a healthy weight.',
      evidence: 'In Austria, the number of overweight young people has increased steadily over the past decade, and health experts say that the growing popularity of fast food chains is one of the key reasons.',
      closing: 'If young people do not learn to make healthier food choices now, they risk developing serious health problems later in life.',
      modelSentences: [
        { text: 'The growing popularity of fast food is one of the main reasons why more and more young people have health problems.', type: 'CAUSE' },
        { text: "Fast food may be cheap and convenient, but it comes at a high cost to young people's health.", type: 'CONTRAST' },
        { text: "One of the most serious consequences of the fast food trend is its effect on teenagers' physical health.", type: 'CLAIM' },
        { text: 'While fast food is often seen as a harmless treat, eating it regularly can lead to serious health issues for young people.', type: 'CONTRAST' },
        { text: 'The reason so many teenagers struggle with their weight is directly connected to how often they eat fast food.', type: 'CAUSE' },
      ] },
  ],
  tasks: [
    { id: 'socialmedia', title: 'Task 1: Social Media & Mental Health',
      prompt: '"Social media has changed the way young people communicate. Discuss the impact of social media on teenagers\' mental health."',
      instruction: 'Write ONE complete body paragraph addressing this topic. Use all four layers.',
      model: {
        point: "Social media can be very harmful to teenagers' mental health.",
        explain: 'Apps like Instagram and TikTok are full of edited photos and perfect-looking lives. When young people see this every day, they start to believe that their own lives are not good enough, which makes them feel unhappy and insecure.',
        evidence: "A 2017 report by the Royal Society for Public Health ranked Instagram as the most harmful social media platform for young people's mental health and body image.",
        closing: 'If platforms do not do more to protect young users, these problems will only get worse in the future.',
      },
      analysis: [
        { part: 'Topic sentence', why: 'Clear and specific: not "Social media is bad" but narrows it down to mental health.' },
        { part: 'Supporting sentence', why: 'Explains the HOW: edited photos → unrealistic expectations → feeling insecure. The reader follows the logic.' },
        { part: 'Evidence', why: 'Names a real, citable study instead of a vague "many experts say...". Only quote a number if you can stand behind it.' },
        { part: 'Closing', why: "Doesn't repeat the topic sentence. Instead, it looks ahead: what happens if nothing changes? That's a real conclusion." },
      ] },
    { id: 'politicians', title: 'Task 2: Politicians on Social Media',
      prompt: '"More and more politicians use social media to share their opinions directly with the public. Discuss whether this is a positive or negative development."',
      instruction: 'Write ONE complete body paragraph addressing this topic. Use all four layers.',
      model: {
        point: 'One serious problem with politicians using social media is that they can spread false information without anyone checking it first.',
        explain: 'On platforms like X or Instagram, there are no journalists or editors who verify what is being posted. This means that politicians can make claims that sound convincing but are not actually true, and millions of people will see them instantly.',
        evidence: 'For example, during elections in the US and Europe, many political posts were later found to contain false or misleading statements, but by then they had already been shared thousands of times.',
        closing: 'This makes it harder for voters to tell the difference between facts and opinions, which is a real danger for democracy.',
      },
      analysis: [
        { part: 'Topic sentence', why: 'Uses the CLAIM formula: identifies one specific problem (false information). Keeps it simple and focused.' },
        { part: 'Supporting sentence', why: 'Explains the mechanism in plain language: no fact-checking → false claims → millions see them. Easy to follow.' },
        { part: 'Evidence', why: "Uses a general but concrete example (elections in US and Europe). You don't need to name one person – the pattern is enough." },
        { part: 'Closing', why: "Adds a real consequence: voters can't tell facts from opinions. The paragraph ends on a bigger idea, not a repetition." },
      ] },
    { id: 'climate', title: 'Task 3: Climate & Lifestyle',
      prompt: '"Many people argue that individual lifestyle choices can help fight climate change. Discuss whether personal actions like eating less meat or avoiding flights can make a real difference."',
      instruction: 'Write ONE complete body paragraph addressing this topic. Use all four layers.',
      model: {
        point: 'Individual lifestyle choices can make a difference because they change what companies produce and sell.',
        explain: 'When many people decide to eat less meat or to take the train instead of a flight, businesses notice and start to offer more climate-friendly options. This creates a cycle: the more people buy sustainable products, the cheaper and more available they become.',
        evidence: 'In Austria, for example, the demand for plant-based food has grown so much that supermarkets like BILLA and SPAR now have large vegan sections that did not exist five years ago.',
        closing: 'Even small choices can add up to big changes when enough people make them at the same time.',
      },
      analysis: [
        { part: 'Topic sentence', why: 'Uses a CAUSE formula: personal choices matter BECAUSE they change what companies do. A clear argument in one sentence.' },
        { part: 'Supporting sentence', why: 'Explains the logic step by step: people buy differently → companies adapt → products become cheaper. The chain makes sense.' },
        { part: 'Evidence', why: 'Uses a local, relatable example (BILLA, SPAR). Your examiners will notice you are not recycling generic facts.' },
        { part: 'Closing', why: "Short and punchy. Doesn't repeat the topic sentence but zooms out: small + many = big. A satisfying ending." },
      ] },
  ],
  phraseGroups: [
    { label: 'Starting a paragraph', phrases: ['To begin with,…', 'First and foremost,…', 'One of the main reasons for this is…', 'A key factor to consider is…', 'It is widely acknowledged that…', 'While many argue that…, the evidence suggests…'] },
    { label: 'Explaining / developing', phrases: ['This is largely because…', 'The main reason for this is that…', 'This can be explained by the fact that…', 'In other words,…', 'What this means in practice is that…', 'This suggests that…'] },
    { label: 'Introducing evidence', phrases: ['According to…', 'Research shows that…', 'Studies have found that…', 'It has been reported that…', 'A recent survey by… found that…', 'For example,…', 'For instance,…'] },
    { label: 'Closing a paragraph', phrases: ['This clearly demonstrates that…', 'It is therefore evident that…', 'This leads to the conclusion that…', 'Given this evidence, it is difficult to argue that…', 'This highlights the need for…', 'Unless something changes,…'] },
  ],
  recipe: [
    { num: '1', title: 'Start with a SPECIFIC claim', desc: 'Not a vague observation. Name the exact problem, cause, or consequence you are arguing.' },
    { num: '2', title: 'Explain the WHY or HOW', desc: 'Build the logic step by step. Your reader should be able to follow the chain of reasoning.' },
    { num: '3', title: 'Use CONCRETE evidence', desc: 'Names, numbers, places. A real study or local example is always stronger than "many experts say…"' },
    { num: '4', title: 'Close with a CONSEQUENCE or NEW INSIGHT', desc: 'Never repeat yourself. Look ahead: what happens next? What does this prove? Zoom out.' },
  ],
  goodVsWeak: {
    strong: 'Individual lifestyle choices can make a difference because they change what companies produce and sell. When many people decide to eat less meat, businesses notice and start offering more sustainable options. In Austria, demand for plant-based food has grown so much that supermarkets like BILLA and SPAR now have large vegan sections that did not exist five years ago. Even small choices can add up to big changes when enough people make them at the same time.',
    weak: 'Individual choices are important. Many people say that what we do in daily life matters. Some experts think that eating less meat is good. So people should make better choices because this is important for the environment and for our future.',
    diffs: [
      'The weak paragraph has no concrete topic sentence – "individual choices are important" says nothing specific.',
      'It uses vague attribution ("many people say", "some experts think") instead of actual evidence.',
      '"This is important for our future" is a non-conclusion – it repeats a vague claim instead of drawing a real consequence.',
      'The strong paragraph names real places (BILLA, SPAR), explains a mechanism (people buy → companies adapt), and ends with a new insight.',
    ],
  },
};
