/* ════════════════════════════════════════════════════════════
   SRDP Matura Writing Guide – Content Data (Part 4: page content)
   Vorher als Literale in den pages-*.js-Dateien. Hier liegt nur Inhalt,
   gerendert wird in pages-*.js. PDF-Export und Prüfskript lesen dieselben Daten.
   ════════════════════════════════════════════════════════════ */

SRDP.typeExamples = {
  essay: { weak: 'Social media has many advantages and disadvantages for young people today.', strong: 'For teenagers, the real cost of social media is a slowly shrinking attention span.', why: 'A strong essay opens each paragraph with one clear point that you can argue for. The weak version mentions advantages and disadvantages but takes no position, so the examiner cannot follow your line of argument.' },
  article: { weak: 'In this article I am going to tell you about the advantages of doing sport.', strong: 'Ask anyone who has hit the wall at kilometre 30: running is at least half a mental game.', why: 'An article has to pull the reader in. Announcing your plan sounds flat, while a concrete hook makes someone want to read on.' },
  report: { weak: 'I really think the school canteen is terrible and nobody likes it.', strong: 'Key findings: 68 per cent of the 120 students surveyed rated the canteen food as poor or very poor.', why: 'A report stays factual and presents its evidence under meaningful headings. Personal outbursts cost you marks because the register is wrong.' },
  blog: { weak: 'One should carefully consider the various advantages before deciding to take a gap year.', strong: 'I used to think a gap year was just an expensive way to put off real life. Then I took one, and it changed my mind.', why: 'A blog needs a personal, informal voice, with contractions and a short story. A formal phrase like "one should consider" belongs in a different text type.' },
  email: { weak: 'Hi! Your headphones broke after two days and I want my money back, thanks.', strong: 'Dear Sir or Madam, I am writing to request a refund for the headphones I bought on 3 May, which stopped working after two days.', why: 'A formal e-mail names its purpose in the first line and keeps a polite, formal register throughout. The casual version would be marked down for register and tone.' },
  leaflet: { weak: 'This leaflet provides information about the annual town festival taking place in the market square.', strong: 'Live music, free food and the whole town in one square: the Seetal Festival is back, and you are invited.', why: 'A leaflet has to catch the attention of someone who looks at it for two seconds at a bus stop. The weak version describes itself like a report and gives no reason to read on. The strong version starts with what the reader gets and speaks to them directly.' },
};


SRDP.secondModels = {
  essay: { title:'Should smartphones be banned in schools?', meta:'~400 words · formal', tip:'This second example has no colour labels on purpose. Try to spot the thesis in the introduction, the topic sentence of each body paragraph, the counter-argument and the forward-looking conclusion yourself.', paras:[{ t:'Few objects divide a school as quickly as the smartphone. Some teachers would happily collect every device at the school gate; others hand out tablets and expect us to look things up in seconds. My own view sits between the two. A blanket ban is a mistake: phones cause genuine problems in class, but pretending they do not exist solves nothing, and the realistic option is to control when and how they are used.', mono:false },{ t:'The case for banning phones is easy to understand. A single buzzing notification can pull a whole row of students out of a lesson, and anyone who has sat in a class where half the room is watching TikTok under the desk knows how quickly attention drains away. Cheating has become simpler, too: an answer is only a quick search away. Several schools that locked phones in pouches during the day have reported calmer corridors and livelier conversations at break. These are not small gains, and they deserve to be taken seriously.', mono:false },{ t:'Even so, the device that causes the trouble is also a genuinely useful tool. In our biology lessons we photograph experiments, scan a code to open a quiz, and check unfamiliar words in seconds. A student who has forgotten a deadline can look it up; one who finds reading hard can have a text read aloud. Banning the phone outright throws all of this away, and it teaches nothing about self-control. Teenagers who never manage their phones at school simply postpone that struggle until later.', mono:false },{ t:'Supporters of a full ban often reply that teenagers cannot be trusted to regulate themselves, and there is some truth in that. Willpower rarely wins against a well-designed app. The better answer, though, is to build in structure. Phones can stay switched off and out of sight by default, and come out only for a clear purpose when a teacher asks for them. Rules that we help to write are far harder to resent than ones simply imposed from above.', mono:false },{ t:'On balance, I remain convinced that banning smartphones treats a symptom while ignoring the cause. My generation will carry these devices into every job and every waiting room for the rest of our lives. A school that shows us how to switch off, focus, and then use the tool on purpose gives us something a locked pouch never can.', mono:false }] },
  article: { title:'Why learning a language is worth the struggle', meta:'~250 words · semi-formal', tip:'This second example has no colour labels. Try to spot the catchy opening question, the personal voice, and the way each paragraph develops one clear idea yourself.', paras:[{ t:'Have you ever given up on a language because the grammar felt impossible? You are not alone. But after spending a summer working in Italy with barely any Italian, I am convinced that pushing through the hard part is one of the most rewarding things a teenager can do.', mono:false },{ t:'The obvious benefit is communication. Once I could order food, ask for directions and joke with my colleagues, a whole country opened up to me. Suddenly I could actually take part instead of staring helplessly at a menu like a tourist. I will never forget the afternoon an elderly shopkeeper, delighted that a foreigner was even trying, spent twenty minutes teaching me the local word for delicious. That single afternoon taught me more than a month of vocabulary lists ever could.', mono:false },{ t:'What surprised me more, though, was what it did to my confidence. Every small conversation I survived made the next one a little easier. I slowly realised that making mistakes was not embarrassing at all, just part of the process. By the end of the summer, the language had stopped feeling like a school subject and started feeling like a tool I actually owned.', mono:false },{ t:'So if you are ever tempted to quit, my advice is simple: keep going, and look for chances to use the language in real life, even when it feels awkward. The struggle is temporary, but the doors a second language opens stay open for good.', mono:false }] },
  report: { title:'Report on the use of the school library', meta:'~250 words · formal', tip:'This second example has no colour labels. Try to spot the header, the clear section headings, the precise data and the recommendations yourself.', paras:[{ t:'Date: 8 May 2026\nFrom: Tom Pichler, Student Council\nSubject: Survey on the Use of the School Library', mono:true },{ t:'Aim of the survey\nThis report presents the results of a survey on how students use the school library. A total of 110 students from years 5 to 8 took part. The aim is to find out why the library is so often empty and to suggest practical improvements.', mono:false },{ t:'How students use the library\nThe results were revealing. While 78% of respondents said they valued having a library, only 21% visited it more than once a month. The main reasons given were limited opening hours and a lack of quiet study space. Interestingly, students in the upper years were far more likely to use the library than younger ones, who tended to study at home. In addition, many were unaware that e-books could be borrowed free of charge. When asked what would bring them in more often, most pointed to comfortable seating and a wider choice of books.', mono:false },{ t:'Suggested improvements\nOn the basis of these findings, it would be advisable to extend the opening hours into the early afternoon and to create a separate silent study area. Furthermore, the e-book service should be promoted more actively, for example through posters and a short presentation in each class. It would also be worth repeating the survey after one term to measure the effect.', mono:false },{ t:'Conclusion\nIn summary, students clearly value the library but rarely use it. With longer hours, a dedicated quiet zone and better promotion, it could once again become a valuable part of school life.', mono:false }] },
  blog: { title:'What three months without takeaway taught me', meta:'~250 words · informal', tip:'This second example has no colour labels. Try to spot the username line, the chatty personal voice, the short sentences and the call to comment yourself.', paras:[{ t:'by leo_cooks · 14 April 2026, 18:20\n\nWhat Three Months Without Takeaway Taught Me', mono:true },{ t:'Confession time: until March, I ordered food about four times a week. Pizza, sushi, burgers, you name it. Then my mum challenged me to cook every single meal myself for three months, and I said yes mostly to prove her wrong. My friends laughed. My brother even started a betting pool on how long I would last, and the longest guess was nine days. Spoiler: I did not starve, and he lost ten euros.', mono:false },{ t:'Week one was a disaster. I burnt rice, undercooked chicken and somehow set off the smoke alarm twice. But nobody tells you this: cooking gets easier scarily fast. By week three I could throw together a curry without even checking the recipe, and it actually tasted good. Somewhere around week six, I even started to enjoy it. There is something weirdly satisfying about eating a meal you made with your own two hands, even if half of it is slightly burnt.', mono:false },{ t:'The biggest surprise, though, came when I checked my bank account at the end of the challenge. I worked out that I had saved almost 200 euros, just by not tapping that little delivery button. Will I order takeaway again? Sure, and I did, last Friday. But now it feels like a treat instead of a lazy default. Have you ever tried a challenge like this? Tell me how it went in the comments!', mono:false }] },
  email: { title:'Complaint about a faulty online order', meta:'~250 words · formal', tip:'This second example has no colour labels. Try to spot the four-part header, the formal greeting, the specific complaint, the clear request and the matching sign-off yourself.', paras:[{ t:'To: support@techstore.example\nFrom: julia.berger@email.example\nDate: 22 April 2026\nSubject: Faulty Wireless Headphones (Order #48217)', mono:true },{ t:'Dear Sir or Madam,\n\nI am writing to complain about a pair of wireless headphones I ordered from your website on 5 April. Although the product was advertised as new and fully functional, it developed a serious fault within only three days of use. As I had been looking forward to using them for my daily commute, the disappointment was considerable.', mono:false },{ t:'To be specific, the right earpiece stopped working completely, and the battery now lasts barely an hour despite a full charge. I have carefully followed the troubleshooting steps on your website, but unfortunately none of them solved the problem. I should add that this is the second item from your shop to develop a fault within a month, which has understandably shaken my confidence in the products you sell. Naturally, I expected an item advertised as new to last considerably longer than a few days of normal use.', mono:false },{ t:'Before contacting you in writing, I had already telephoned your customer service line twice, on 9 and 14 April, but on both occasions I was merely promised a callback that never arrived. As the headphones are clearly defective, I would therefore like to request either a full refund or a replacement of the same model. Given that the order is still well within its warranty period, I trust this can be resolved quickly. I have attached a copy of my order confirmation and look forward to your reply within 14 days.\n\nYours faithfully,\nJulia Berger', mono:false }] },
  leaflet: { title:'Recycle Right – The New Kerbside Scheme for Seetal', meta:'~250 words · persuasive', tip:'This second example has no colour labels on purpose. Try to spot the catchy title, the subheadings that tell readers what they gain, the direct address, the call to action and the block of practical details yourself.', paras:[{ t:'Recycle Right – The New Kerbside Scheme for Seetal', mono:false },{ t:'Good news for the planet and for your Saturday mornings: from Monday, 7 September, Seetal collects your recycling straight from your doorstep. No more trips to the bottle bank in the rain, no more overflowing cupboards under the sink. Here is everything you need to know.', mono:false },{ t:'Three Bins, One Simple System\nYou will receive three colour-coded bins: blue for paper, yellow for plastic and metal, and green for glass. Just sort as you go and wheel them out on collection day; the lorry comes every second Monday, and a fridge magnet with all the dates is included. Every correctly sorted bin helps keep our lakes and forests clean.', mono:false },{ t:'What Goes Where?\nNot sure if that yoghurt pot counts? Every bin comes with a clear sticker showing what belongs inside, and our website has a quick search tool for the tricky items. When in doubt, look it up rather than guessing – one wrong item can spoil a whole load.', mono:false },{ t:'Start Today – It Costs You Nothing\nThe scheme is completely free for every household in Seetal. Sign up online in two minutes and your bins arrive within a week. Anyone without internet access can simply call the town office, and we will register you over the phone. Do it before the September rush and help us make Seetal the greenest town in the valley.', mono:false },{ t:'Collection starts: Monday, 7 September\nSign up: www.seetal-recycelt.example\nQuestions: call the town office on 01 234 5678', mono:true }] },
};


/* Overview: the 8 most expensive mistakes – [mistake, what it costs, the fix] (HTML erlaubt) */
SRDP.mistakes = [
  ['Writing only 2 of 3 content points', 'Task Achievement drops sharply', 'Tick off each content point as you write it'],
  ['Ignoring the text type&rsquo;s rules (e.g. a report without headings)', 'Task Achievement drops – conventions are part of the criterion', 'Check the Layout box in the guide before you start'],
  ['Copying words from the prompt or the input material', 'Range drops: copied language does not count as your own', 'Rephrase, then interpret: what does the figure mean for your point?'],
  ['Word count more than 10% too long or too short', 'Task Achievement drops one band', 'Count your words. Practise estimating.'],
  ['Formal style in a blog (or vice versa)', 'Wrong register costs marks (it is not counted as an Accuracy error)', 'Decide: formal or informal? Then keep to it.'],
  ['Only simple linking words', 'Low Coherence score', 'Use the B2 linking words table'],
  ['No topic sentences', 'Paragraphs feel random, weak Coherence', 'First sentence of each paragraph = the point'],
  ['Forgetting to proofread', 'Errors you would catch in 3 minutes', 'Keep about 15 minutes at the end'],
];


SRDP.faq = [
  /* Quellen (Stand 05.10.2026): matura.gv.at (Prüfungstermine, LFS-Seite, Kompensationsprüfungen),
     Begleittext zum Bewertungsraster B2 (2023), Korrektur- und Beurteilungsanleitung SRP LFS (Sept. 2024),
     Hinweise zur Durchführung AHS/BHS (März 2026), Aufgabenhefte HT 2026, RIS (PO-AHS, PO-BMHS, SchUG).
     Antworten ohne offizielle Quelle sind als Praxistipp formuliert und verweisen auf die Lehrkraft. */
  { q: "When is the written English Matura in 2027?",
    a: "The main date is Tuesday, 11 May 2027, for AHS and BHS. The autumn date is Friday, 17 September 2027, and the winter date is Wednesday, 12 January 2028. These dates are on the official list at matura.gv.at. Your school tells you the start time and the room." },
  { q: "How do my band scores become a grade?", schools: ['ahs'],
    a: "Each of your two texts is rated on four criteria from 0 to 10. That makes eight band scores and 80 points at most. They are converted into the 25 points of the Writing section: your total ÷ 80 × 25. The Klausur has four sections of 25 points each. To pass, you need at least 60 of 100 points, and at least 25 points in each area: reading + listening, and language in use + writing. From 90 points you get a Sehr gut, from 80 a Gut, from 70 a Befriedigend and from 60 a Genügend. Example: band 6 on all eight criteria gives 15 of 25 points in Writing, which is 60%." },
  { q: "How do my band scores become a grade?", schools: ['bhs'],
    a: "Each of your three texts is rated on four criteria from 0 to 10. That makes twelve band scores and 120 points at most. They are converted into the 50 points of the Writing section: your total ÷ 120 × 50. Reading and listening count 25 points each. To pass, you need at least 60 of 100 points, and at least 25 points in each area: reading + listening, and writing. From 90 points you get a Sehr gut, from 80 a Gut, from 70 a Befriedigend and from 60 a Genügend. Example: band 6 on all twelve criteria gives 30 of 50 points in Writing, which is 60%." },
  { q: "What happens if I write too few or too many words?", schools: ['ahs'],
    a: "You can be 10% under or over the target. For a task of about 250 words, that means 225 to 275 words. For about 400 words, it means 360 to 440. If your text is shorter or longer than that, Task Achievement drops by one band. This rule is part of the official assessment scale. Inside the range, a longer text does not score higher. After each task, the exam paper asks you to count your words and write the number down. Practise estimating: count the words in one full line, count your lines and multiply." },
  { q: "What happens if I write too few or too many words?", schools: ['bhs'],
    a: "You can be 10% under or over the target. For a task of about 250 words, that means 225 to 275 words. If your text is shorter or longer than that, Task Achievement drops by one band. This rule is part of the official assessment scale. Inside the range, a longer text does not score higher. After each task, the exam paper asks you to count your words and write the number down. Practise estimating: count the words in one full line, count your lines and multiply." },
  { q: "Do I have to write a fair copy?",
    a: "No. Everything on your sheets is marked unless you cross it out. So cross out your notes and plans before you hand in. Each task also has a box for notes, and that box is not marked. Use the time you save for proofreading." },
  { q: "Can I write the exam on a computer?",
    a: "Some schools hold the written Matura on computers. Ask your teacher how your school does it. If you write on a computer, the exam paper tells you to set up a header with your name, class and page number before you start, and to copy the layout template into your document. Internet, messaging and AI tools are blocked or not allowed." },
  { q: "Can I use a dictionary?",
    a: "It depends on your school type. At AHS, no dictionaries or reference books are allowed in any part of the exam, and that includes electronic ones. At BHS, dictionaries (also electronic ones) are allowed, but only in the Writing section. The tasks are written so that B2 vocabulary is enough. If a word does not come, describe it in other words. The assessment scale rewards that." },
  { q: "Can I use AI tools in the exam?",
    a: "No. The official rules for the written Matura forbid any AI-based application, online or offline. For practice at home, AI can help: the self-check on this site builds a prompt that asks an AI tool for feedback on your text. If your school has its own rules about AI, follow them." },
  { q: "Do contractions (don't, it's) cost marks?",
    a: "Not automatically. The scale checks whether your register fits the text type. In a blog or an informal e-mail, contractions are right. In a report or a formal e-mail they make your register too casual. One contraction will not cost you a band, but a text full of them shows that you do not notice the difference. Decide before you write: formal or informal? Then stay with it." },
  { q: "What if I completely misread the task?",
    a: "The real danger is a text that does not answer the task at all, for example an off-topic text or one you clearly prepared in advance. Then the veto rule applies: Task Achievement gets 0 and the other three criteria are not marked. Writing the wrong text type does not trigger the veto on its own, but it costs a lot of marks in Task Achievement. Protect yourself in one minute: read the task twice and underline the text type, the reader and the three content points." },
  { q: "Can I invent facts, numbers and experiences?",
    a: "Yes. This is a language exam. The official guidance counts content as relevant when it serves the task, even if it is not what the examiner expected. An invented survey or a made-up summer job in Italy is fine, as long as it sounds realistic and develops a content point. Content that has nothing to do with the task does not help." },
  { q: "Do British and American spelling both count?",
    a: "Both are generally accepted, although the official rules do not say so directly. Colour or color, organise or organize: either is fine. Do not mix the two systems in one text, because that looks like guessing. Use the one you know best (for most Austrian students that is British English). If you want to be sure for your school, ask your teacher." },
  { q: "What if I do not finish a task?",
    a: "An unfinished text does not get an automatic zero. It is marked with the same scale, and what is on the page counts. But it usually loses marks in Task Achievement (content points not developed) and in Coherence (no ending). Plan your time before you start writing: decide when each task must be finished. If time runs out, a shorter complete text is better than a long one without an ending." },
  { q: "Can I add ideas beyond the three content points?",
    a: "You can, and extra relevant ideas are not punished. But the scale rewards developing all three content points in about the same depth. Every sentence you spend on a fourth idea is missing from the three content points, and it uses up your word count. Build your text around the three content points and add extras only when those are done." },
  { q: "Is the title part of the word count?",
    a: "There is no clear public rule, and schools may count differently. A title is only a few words, so it rarely makes a difference. If you are close to the limit, cut repetition instead. If you want to know how your school counts, ask your teacher." },
  { q: "Which task should I write first?",
    a: "You decide. The exam paper does not set an order. Plan a time slot for each task before you start, begin with the text type you feel most sure about, and keep about 15 minutes at the end to proofread everything. Decide your order before exam day." },
  { q: "Are the tasks the same at every school?",
    a: "At AHS, yes. The tasks come centrally from the BMB, and all AHS candidates get the same paper on the same day. At BHS, the writing tasks are written for each school type (HAK, HTL, HUM and others), so a HAK paper differs from an HTL paper. Either way, the official past papers at matura.gv.at are good practice material." },
  { q: "What happens if I fail the written exam?",
    a: "You can take an oral compensation exam (Kompensationsprüfung). You have to register for it within three days after you hear your grade. You get at least 30 minutes to prepare, and the exam takes at most 25 minutes. After a compensation exam, the best possible grade is Befriedigend. If you do not pass it, you can repeat the written exam at a later date. Your teachers explain the details if it comes to that." },
];


SRDP.honest = {
  essay: {
    title: 'Should the school day start later?',
    meta: '~300 words · a realistic borderline text, not a model',
    intro: 'The other model texts on this site show strong writing. This one is a realistic borderline text: a believable student essay close to the B2 line, with the places where it loses marks. (A single text does not pass or fail on its own; the grade comes from the whole exam. But every band you lose here has to be made up somewhere else.) The numbered markers explain what each weak spot costs and how a stronger version would sound.',
    paras: [
      "Everybody knows that teenagers are always tired in the morning.{{1}} In Austria the school starts{{2}} at eight o'clock and many students must get up at six. In this essay I want to write about the question if the school day should start later.{{3}}",
      "The first point is sleep.{{4}} Scientists say that teenagers need around nine hours of sleep, but most of them only get seven hours. Since three years{{5}} I go to school by bus and I see every morning students which{{6}} are sleeping on the bus. When school would start{{7}} at nine, everybody could sleep one hour more. This would be very good for the health and also for the marks, because tired students cannot concentrate good{{8}} in the lessons.",
      "The second point is free time.{{4}} When school starts later, it also ends later, and this is a problem for students who do sports or play an instrument. My training for example starts at five. So a later start is maybe not so good for these students, it is really annoying for them.{{9}} On the other hand, they could do their homework in the morning, when the brain is fresh.",
      "The third point is the family. Many parents must go to work at eight, and they bring the small children to school before. When the school starts later, the parents have a problem, because they cannot bring the children. So a later start is good for the teenagers but not so good for the parents. This is a big problem and it is very important to think about it.{{10}}",
      "All in all I think that the school should start later, because sleep is very important for teenagers.{{11}} Maybe nine o'clock is too late, but half past eight would be a good compromise. It is very important that the politicians think about this question.{{12}}",
    ],
    notes: [
      "'Everybody knows that…' is a very weak opening: it says nothing new and has no angle. Stronger: a concrete image or a surprising fact ('At 7:15, half my bus is asleep.').",
      "Article error, straight from the Grammar kit: German 'die Schule' pulls in a wrong 'the'. It's 'school starts', no article – institution used for its purpose.",
      "Announcing your plan ('In this essay I want to write about…') wastes the whole introduction. State a thesis instead: take a position in one clear sentence.",
      "'The first point is sleep.' is a label, not a topic sentence. It costs Coherence marks because it doesn't say anything the paragraph will prove. Stronger: 'The strongest argument for a later start is simple biology: teenagers are wired to sleep late.'",
      "'Since three years' – the classic since/for trap. English needs 'for three years' (duration) and would prefer a present perfect: 'For three years I have been taking the bus…'.",
      "'students which' – people take 'who', not 'which'. Small error, but it repeats through the text, and repeated basic errors drag Accuracy below band 6.",
      "'When school would start at nine' – a double conditional error: 'when' instead of 'if', and 'would' inside the if-clause. B2 wants 'If school started at nine, everybody could…'.",
      "'concentrate good' – adverb needed: 'concentrate well' (or 'properly'). Adjective/adverb confusion is a very common mistake and easy to fix when you proofread.",
      "Register slip: 'it is really annoying for them' is spoken language in a formal essay. The idea is fine, but the wording costs Range marks. Formal version: 'for these students, a later start would create serious scheduling conflicts.'",
      "Empty intensifiers ('a big problem', 'very important') appear five times in this text. Each one is a missed chance for precise B2 language: 'a real dilemma for working parents' is precise; 'a big problem' is not.",
      "The conclusion only repeats the introduction's point about sleep and drops the other two arguments. A strong conclusion weighs all three and lands on a position.",
      "Ending on 'the politicians should think about it' hands the decision to someone else. The task asks what you think, so say it: 'Starting at half past eight would cost little and give students half an hour more sleep.'",
    ],
    verdict: "Task Achievement for the content around 6 – all three points are addressed with some development, conventions are basically there. Coherence around 5–6 – paragraphs exist, but label-style topic sentences and a repetitive conclusion weaken the line of thought. Range and Accuracy around 4–5 each: simple structures dominate, intensifiers repeat, and the since/for, article and if-clause errors are frequent ones that you can fix with practice. One problem the numbered markers do not show: at about 300 words this essay is well under the ~400 the task asks for (more than 10% too short), so Task Achievement ends up one band lower than the figure above.",
  },
  email: {
    title: 'Complaint about a delayed delivery',
    meta: '~150 words · a realistic borderline text, not a model',
    intro: 'Another realistic borderline text: this formal e-mail is close to the B2 line, but it loses marks in a dozen small places. The markers show where, and what a stronger version would do instead.',
    paras: [
      "To: office@citysports.example\nFrom: lukas.maier@email.example\nDate: 12 March 2026\nSubject: Problem{{1}}",
      "Dear Sir or Madam,",
      "I am writing to you because I have a problem with my order.{{2}} Three weeks ago I ordered a pair of running shoes on your website. On the website it said{{3}} that the delivery takes three or four days, but until today{{4}} I didn't receive{{5}} anything.",
      "I already wrote two informations{{6}} to your service team, but I didn't get an answer. This is not okay for me.{{7}} I need the shoes for a running competition, which is in two weeks, and slowly I am getting nervous.{{8}} I don't{{9}} understand how a delivery can take so long when your website promises something else.",
      "So I want my money back or the shoes until next week.{{10}} I hope you understand my situation and that we can find a good solution together.",
      "I look forward to hear{{11}} from you.",
      "Best wishes,{{12}}\nLukas Maier",
    ],
    notes: [
      "A one-word subject line ('Problem') wastes the first impression and costs Task Achievement points on the title/subject descriptor. Strong: 'Delayed delivery of order #58291 – request for refund'.",
      "The purpose sentence is there (good!) but vague. Name the facts in line one: 'I am writing to complain about a delivery that is now three weeks overdue (order #58291).'",
      "'On the website it said' is fine in speech, but far too casual for a formal complaint. Formal: 'Your website states that…'. Register slips like this cost marks, even though the grammar is correct.",
      "'until today' – German 'bis heute'. English: 'to this day' or simply 'I have still not received anything'.",
      "Tense: 'I didn't receive anything' closes the event; the waiting continues, so present perfect is needed: 'I have not received anything.' Austrian students often get the present perfect wrong, so check it when you proofread.",
      "'two informations' – 'information' is uncountable, and it's the wrong word anyway: 'I have already contacted your service team twice.'",
      "'This is not okay for me' – spoken register in a formal complaint. Formal complaints use understatement: 'I find this lack of response disappointing.'",
      "'slowly I am getting nervous' – direct translation of 'langsam werde ich nervös', and too personal for the genre. Formal: 'the matter is now becoming urgent.'",
      "Contractions ('don't', 'didn't') are fine in a blog – in a formal complaint they pull the register down. Written out, the same sentence sounds professional.",
      "The demand is the right move (clear request!) but the tone tips into rude and the deadline is unclear. Formal: 'I would therefore ask you either to deliver the shoes by 20 March or to refund the full amount.'",
      "'look forward to hear' – after 'look forward to', English needs the -ing form: 'I look forward to hearing from you.' Learn it as a fixed phrase.",
      "'Best wishes' after 'Dear Sir or Madam' breaks the pairing rule: unknown name → 'Yours faithfully'. The closing is easy to check.",
    ],
    verdict: "Task Achievement for the content around 6 – purpose, complaint and request are all there, but the subject line and the wrong greeting/closing pair cost points. Coherence 6 – the order of ideas is actually fine. Range 5 – the register keeps slipping into spoken German-English. Accuracy 4–5 – 'informations', 'to hear', tense choices. This is a borderline text with no safety margin, and almost all of its errors are covered in the Grammar kit. At about 150 words it is also far under the ~250 target, so Task Achievement ends up one band lower than the figure above.",
  },
  leaflet: {
    title: 'Information about the Charity Run',
    meta: '~140 words · a realistic borderline text, not a model',
    intro: 'A realistic borderline text for the leaflet. It lands just below the B2 line and loses marks in typical places: a flat, report-style title, no subheadings and no real call to action. The markers show where.',
    paras: [
      "Information about the Charity Run{{1}}",
      "Our school organises a charity run and we want that many people are coming.{{2}} In this leaflet I give you some informations{{3}} about the event.",
      "The run is since three years{{4}} a tradition at our school. Last year we collected over 2,000 Euro for a local animal shelter, and this year we want to collect even more. If you take part, you help animals who has{{5}} no home. You can run 5 or 10 kilometres, it depends on you.{{6}} There is also music and a buffet with cakes and drinks.",
      "The atmosphere is always great and it makes a lot of fun.{{7}} Your family and friends can come and watch too. So I think everybody should come, because it is for a good thing and also very funny.{{8}}",
      "It would be nice if many people come.{{9}}",
    ],
    notes: [
      "A leaflet needs a title that pulls the reader in and short sections with their own subheadings. This one has a flat, notice-style title and runs as a single block with no subheadings at all. That costs Task Achievement.",
      "'we want that many people are coming' is German word order ('wir wollen, dass...'). English: 'we want many people to come'. And 'In this leaflet I give you information' is flat – a leaflet opens with a hook, not a table of contents.",
      "'informations' does not exist – 'information' is uncountable.",
      "'is since three years' – the classic since/for trap, plus tense: 'has been a tradition for three years'.",
      "'animals who has no home' – animals take 'that', and it needs plural agreement: 'animals that have no home'.",
      "'You can run 5 or 10 kilometres, it depends on you.' is a comma splice (two complete sentences joined by only a comma). Use a full stop, and show the reader the benefit: 'Choose 5 or 10 kilometres, whatever suits you.'",
      "'it makes a lot of fun' is a direct translation of 'macht Spaß'. English: 'it is a lot of fun' or 'great fun'.",
      "'very funny' is a false friend: funny = lustig (comical). Here you mean 'fun' (enjoyable).",
      "The biggest gap: there is no call to action and no practical details. A leaflet must tell the reader what to do and give the facts: When? Where? How do I sign up? Ending on 'it would be nice if many people come' leaves the reader with nothing to act on.",
    ],
    verdict: "Task Achievement for the content around 4–5 – the content is there, but the missing subheadings, the missing call to action and the missing date/time/place are leaflet conventions the grid looks for. Coherence around 5 – one undivided block. Range and Accuracy around 4 each: simple sentences plus the frequent, fixable German-into-English errors above. At about 140 words it is also under the ~250 the task expects, so Task Achievement ends up one band lower than the figure above. Clear subheadings and a real call to action would raise the score quickly, and neither needs more advanced English.",
  },
  article: {
    title: 'Social media – curse or blessing?',
    meta: '~200 words · a realistic borderline text, not a model',
    intro: "A realistic borderline text for the article. It answers a school-magazine task, but it reads more like a flat essay than an article, and a few German structures sneak in. The markers show where it loses marks and what a stronger version would do.",
    paras: [
      "Today everybody is talking about social media, and everybody has an opinion.{{1}} In this article I want to show you the good and the bad sides.{{2}} For young people like us it is really an important topic.",
      "Let us start with the good sides. Social media helps us to stay in contact with our friends, also when they live far away. Since two years my cousin lives{{3}} in Spain, and without Instagram I would never know what she is doing. We can also learn a lot, because there are many informations{{4}} about every topic you can imagine. And honestly, it makes a lot of fun{{5}} to watch videos after a long day in the school.{{6}}",
      "But of course there are bad sides too. Many students look at their phone the whole day and cannot concentrate proper{{7}} anymore. Others get real problems with their self-confidence, they compare themselves the whole time with perfect pictures.{{8}} My little brother is only thirteen and already he cannot put the phone away.",
      "All in all, social media has good and bad sides, and everybody must find the right balance. For me it is a great thing, but we should never forget the real life.{{9}}",
    ],
    notes: [
      "A school-magazine article depends on its opening: a question, an image, a surprising claim. 'Today everybody is talking about...' is a flat, essay-style opener with no angle, and it costs Task Achievement on article conventions. Stronger: 'Be honest – how many times did you check your phone before this sentence?'",
      "Announcing the structure ('In this article I want to show you...') is an essay habit. An article pulls the reader straight in without describing its own plan.",
      "'Since two years my cousin lives...' – the since/for trap plus a tense error. English needs duration with 'for' and a present perfect: 'For two years my cousin has been living in Spain.'",
      "'many informations' – 'information' is uncountable and never takes an -s: 'there is a lot of information'.",
      "'it makes a lot of fun' is a straight translation of 'macht Spaß'. English does not 'make' fun: 'it is a lot of fun' or 'great fun'.",
      "'a long day in the school' – German 'in der Schule'. When the building is used for its purpose, English drops the article: 'at school'.",
      "'concentrate proper' – an adverb is needed: 'concentrate properly'. Adjective/adverb slips are very common and easy to catch when you proofread.",
      "'...with their self-confidence, they compare themselves...' is a comma splice: two full sentences joined by only a comma. Split them or add a linking word: '...with their self-confidence, because they constantly compare themselves with perfect pictures.'",
      "'we should never forget the real life' – two things at once: 'the real life' should be 'real life' (no article for a general idea), and the ending is flat. A stronger article ends with a line readers remember: 'Social media is here to stay – the trick is to look up from it now and then.'",
    ],
    verdict: "Task Achievement for the content around 5–6 – the topic is covered and both sides appear, but the flat opening, the announced structure and the weak ending miss the article conventions the grid rewards. Coherence around 6 – the two-sides plan is clear and easy to follow. Range around 4–5 – simple sentences and empty intensifiers ('really', 'a lot') dominate. Accuracy around 4–5 – the since/for, 'informations', article and adjective/adverb slips are the frequent, fixable kind. And at about 200 words it sits under the length the task sets (around 250), so Task Achievement ends up one band lower than the figure above. With the habits above fixed, the same ideas would score clearly higher.",
  },
  report: {
    title: 'Our school canteen: a student survey',
    meta: '~175 words · a realistic borderline text, not a model',
    intro: "A realistic borderline text for the report. It lands just below the B2 line and loses marks in typical places: a vague subject line, vague headings and a register that keeps slipping. The markers show where.",
    paras: [
      "To: Mr Berger, headmaster\nFrom: The student council\nDate: 5 May 2026\nSubject: The canteen{{1}}",
      "In this report I want to write about{{2}} the situation in our school canteen. Last month a survey was made{{3}} by the student council, and 120 students from all classes have answered our questions. The aim was to find out what the students really think.",
      "The results{{4}}\nMost of the students are not happy with the canteen. Since one year{{5}} the prices are higher, but the quality is the same. Many students said also that there is not enough vegetarian food, this is a big problem for them.{{6}} The waiting time at lunch is much too long, and often the warm meals are already gone. Some also complained that there is no information about allergies on the food.",
      "What we want{{7}}\nWe think that some things must be changed.{{8}} The school should offer more vegetarian meals and open a second counter. Also the prices for a warm meal should go down again. If this would happen{{9}}, the students would be much more happy.{{10}}",
    ],
    notes: [
      "A report subject line must be specific: 'The canteen' says almost nothing. Stronger: 'Survey results and recommendations on the school canteen'.",
      "'In this report I want to write about...' is essay register in a report. A report states its purpose formally and impersonally: 'This report presents the results of a student survey on the school canteen and makes recommendations.'",
      "'a survey was made by the student council' – wrong verb in the passive. Surveys are 'carried out' or 'conducted', not 'made': 'A survey was carried out last month.'",
      "'The results' as a section heading says very little. A report needs clear, meaningful headings that help the reader find their way, such as 'Introduction', 'Key findings' and 'Recommendations'. You do not need to number them; the official sample texts do not.",
      "'Since one year the prices are higher' – the since/for trap plus tense. English: 'For a year, prices have been higher.'",
      "'...not enough vegetarian food, this is a big problem for them.' is a comma splice – two full sentences joined by a comma. Split them, and swap the empty 'big problem' for something precise: '...vegetarian food, which was the most frequent complaint.'",
      "'What we want' is an informal heading. In a report this section is headed 'Recommendations', and the tone stays neutral rather than sounding like a wish list.",
      "'We think that some things must be changed' – subjective 'we think' plus a vague, agent-less passive. A report recommends concretely: 'The council recommends the following three changes.'",
      "'If this would happen' – 'would' does not belong in the if-clause. B2 wants 'If this happened' or 'If these changes were made'.",
      "'the students would be much more happy' – the comparative is 'happier', and 'much more happy' is spoken register. A report ends in a neutral tone: 'these measures would noticeably improve satisfaction.'",
    ],
    verdict: "Task Achievement for the content around 5 – the report has a purpose, findings and a recommendation, but the vague subject line and the vague headings cost real marks on report conventions. Coherence around 5–6 – the reader can follow it, though the unlabelled sections make it feel more like a letter than a report. Range around 4–5 – simple sentences and 'big problem'-style filler. Accuracy around 4–5 – the passive, since/for, comma splice and if-clause errors are common ones that practice can fix. At about 175 words it is also under the length the task sets (around 250), so Task Achievement ends up one band lower than the figure above. Better headings and careful proofreading would fix many of these points.",
  },
  blog: {
    title: 'How I taught myself to cook',
    meta: '~215 words · a realistic borderline text, not a model',
    intro: "A realistic borderline text for the blog. The voice is good: informal and personal, with contractions. It loses marks on structure and on the missing call to comment at the end. The markers show where, and which 'errors' are actually fine in a blog.",
    paras: [
      "Okay, I have to be honest with you: two months ago I couldn't even boil an egg without burning something. My mum always cooked for me and I never really thought about it. But then she went for three weeks to my grandma, who was sick, and suddenly I was alone with an empty fridge and a very empty stomach. The first days were a catastrophe. I ordered pizza every evening, and after a while my body just said stop, this is too much.{{1}} So I decided to learn how to cook, and honestly, it changed more than I expected.{{2}}",
      "At first I watched tons of videos and found so many informations{{3}} online that I had no idea where to start. Since two weeks I cook now{{4}} every day, and I've already got three or four dishes that I can make really good.{{5}} The best part isn't even the food, it's the feeling. When you make something with your own hands and it actually tastes nice, you feel really proud. And I'm saving a lot of money, because cooking at home is much cheaper than ordering all the time. My friends couldn't believe it when I cooked dinner for two of them last week. Cooking isn't a talent, it's just practice, and anyone can pick it up.{{6}}",
    ],
    notes: [
      "'...my body just said stop, this is too much.' – two complete sentences with only a comma between them (a comma splice). The chatty voice is right for a blog; the punctuation still is not. Use a full stop or a dash: '...my body just said stop. This was too much.'",
      "This is where the post should break. Blogs usually have short paragraphs, but this text is only two big blocks. A new paragraph should start exactly at the turn from panic to decision. Long blocks of text cost Coherence marks and put readers off.",
      "'so many informations' – 'information' is uncountable and never takes an -s: 'so much information'.",
      "'Since two weeks I cook now every day' – the since/for trap plus German word order. English: 'For two weeks now I have been cooking every day.'",
      "'dishes that I can make really good' – an adverb is needed: 'really well'. (Note that the contractions in this post – couldn't, it's, I've – are all correct here: an informal blog wants them, so they cost nothing.)",
      "This post ends on a neat line but never turns back to the reader: there is no question and no invitation to comment. Add one: 'Have you ever had to learn something from zero like this? Tell me in the comments – I need more recipes.'",
    ],
    verdict: "Task Achievement for the content around 5–6 – it is a genuine, personal story that answers a blog task, but with no headline on the post, no clear reader address and no call to comment at the end, it misses blog conventions the grid rewards. Coherence around 5 – readable, yet the two giant paragraphs work against it. Range around 6 – the informal voice is actually a strength here, with some natural phrasing. Accuracy around 5 – 'informations', the since/for slip and 'really good' are the frequent, fixable kind, and the contractions, correct for a blog, cost nothing. At about 215 words it also sits under the length the task sets (around 250), so Task Achievement ends up one band lower than the figure above. With shorter paragraphs and a question for the reader at the end, it would read like a real blog.",
  },
};


SRDP.topicVocab = [
  { topic: "Environment & climate", words: [
    { w: "climate change", hint: "The long-term change in the Earth's weather patterns. Works as the subject of strong openings: 'Climate change affects every one of us.'" },
    { w: "carbon footprint", hint: "The amount of CO2 your lifestyle produces. Often with 'reduce': 'Flying less is one of the best ways to reduce your carbon footprint.'" },
    { w: "renewable energy sources", hint: "Wind, solar, hydro – energy that does not run out. 'Austria invests heavily in renewable energy sources.'" },
    { w: "greenhouse gas emissions", hint: "The gases that heat up the planet. Usually with 'cut' or 'reduce': 'The EU wants to cut greenhouse gas emissions by 2030.'" },
    { w: "to cut down on waste", hint: "To reduce the amount you throw away. 'Schools could cut down on waste by banning plastic bottles.'" },
    { w: "a throwaway society", hint: "A society that buys, uses and bins things quickly. Good for critical writing: 'We live in a throwaway society.'" },
    { w: "environmentally friendly", hint: "Not harmful to nature. Describes products, habits, choices: 'an environmentally friendly alternative'." },
    { w: "to raise awareness of", hint: "To make people notice a problem. 'The campaign raises awareness of plastic pollution.'" },
    { w: "sustainable development", hint: "Growth that does not destroy resources for the future. A key term in formal texts and reports." },
    { w: "to tackle pollution", hint: "To deal with pollution seriously. 'Tackle' also works with problems, causes, issues." },
    { w: "single-use plastic", hint: "Plastic you use once and throw away – straws, cups, bags. 'The EU has banned many single-use plastics.'" },
    { w: "to combat global warming", hint: "To fight against global warming. More formal than 'fight': perfect for reports and articles." },
  ] },
  { topic: "Social media & technology", words: [
    { w: "to scroll through a feed", hint: "To move through posts on a screen, often mindlessly. 'I caught myself scrolling through my feed for an hour.'" },
    { w: "screen time", hint: "The hours you spend looking at screens. 'Parents worry about their children's screen time.'" },
    { w: "a digital detox", hint: "A planned break from phones and social media. 'A weekend digital detox did me a world of good.'" },
    { w: "to go viral", hint: "To spread extremely fast online. 'The video went viral within hours.'" },
    { w: "an online presence", hint: "How you appear on the internet – profiles, posts, photos. 'Employers check applicants' online presence.'" },
    { w: "to spread fake news", hint: "To pass on false information as if it were true. 'Bots spread fake news faster than humans can correct it.'" },
    { w: "data privacy", hint: "Control over who sees and uses your personal information. 'Teenagers care more about data privacy than adults think.'" },
    { w: "to stay connected", hint: "To keep in contact, especially over distance. 'Social media helps families stay connected across continents.'" },
    { w: "information overload", hint: "Too much information to process. 'Constant notifications lead to information overload.'" },
    { w: "a filter bubble", hint: "An online space where you only see opinions you already agree with. Strong term for writing on social media." },
    { w: "cyberbullying", hint: "Bullying that happens online. 'Victims of cyberbullying cannot simply walk away.'" },
    { w: "to disconnect from devices", hint: "To switch off and step away from technology. 'Learning to disconnect from devices is a skill in itself.'" },
  ] },
  { topic: "Education & school", words: [
    { w: "to sit an exam", hint: "To take an exam (British English). 'Austrian students sit their final exams in May.'" },
    { w: "lifelong learning", hint: "Continuing to learn long after school. A favourite in articles about the future of work." },
    { w: "a heavy workload", hint: "A large amount of work to manage. 'Students complain about a heavy workload in their final year.'" },
    { w: "to fall behind", hint: "To make slower progress than the others. 'Without support, weaker students quickly fall behind.'" },
    { w: "extracurricular activities", hint: "Clubs, sports and projects outside normal lessons. 'Universities value extracurricular activities.'" },
    { w: "distance learning", hint: "Learning from home via the internet. 'Distance learning tested everyone's self-discipline.'" },
    { w: "academic pressure", hint: "Stress caused by the demand for good marks. 'Academic pressure peaks in the Matura year.'" },
    { w: "to broaden your horizons", hint: "To widen your experience and understanding. 'A term abroad broadens your horizons.'" },
    { w: "a well-rounded education", hint: "An education that develops many different skills, not just exam knowledge." },
    { w: "to retake a subject", hint: "To repeat an exam or course you failed. 'She had to retake maths in autumn.'" },
    { w: "peer pressure", hint: "The push to do what people your age do. 'Peer pressure shapes what teenagers wear, watch and buy.'" },
    { w: "to develop key skills", hint: "To build the central abilities you need. Common in formal texts: 'Group projects develop key skills.'" },
  ] },
  { topic: "Health & lifestyle", words: [
    { w: "a balanced diet", hint: "Eating a healthy mix of foods. 'A balanced diet does more than any miracle product.'" },
    { w: "to lead an active lifestyle", hint: "To live in a way that includes regular movement. 'Cycling to school is an easy way to lead an active lifestyle.'" },
    { w: "mental health", hint: "The state of your mind and emotions. 'Schools finally talk openly about mental health.'" },
    { w: "to put on weight", hint: "To become heavier. Neutral phrasing: 'Many students put on weight in stressful phases.'" },
    { w: "a work-life balance", hint: "The balance between job or school and free time. 'A healthy work-life balance prevents burnout.'" },
    { w: "to burn off calories", hint: "To use up energy through movement. 'A brisk walk burns off more calories than you think.'" },
    { w: "a sedentary lifestyle", hint: "A lifestyle with too much sitting. Formal and precise – great for reports on health." },
    { w: "to cope with stress", hint: "To manage stress successfully. 'Sport helps me cope with stress before exams.'" },
    { w: "to stay in shape", hint: "To remain fit. 'You do not need a gym membership to stay in shape.'" },
    { w: "sleep deprivation", hint: "Not getting enough sleep. 'Sleep deprivation ruins concentration faster than any distraction.'" },
    { w: "preventive healthcare", hint: "Medicine that stops illness before it starts – check-ups, vaccinations, healthy habits." },
    { w: "to get into shape", hint: "To become fit (after not being fit). 'He got into shape for the ski season.'" },
  ] },
  { topic: "Work & career", words: [
    { w: "to apply for a job", hint: "To formally ask for a position. 'She applied for a summer job at a local hotel.'" },
    { w: "job satisfaction", hint: "How happy work makes you. 'For many, job satisfaction matters more than salary.'" },
    { w: "a steady income", hint: "Regular, reliable money. 'A steady income gives you freedom to plan.'" },
    { w: "to climb the career ladder", hint: "To move up to better positions. 'She climbed the career ladder within five years.'" },
    { w: "work experience", hint: "Practical experience of working. 'An internship gives you valuable work experience.'" },
    { w: "a nine-to-five job", hint: "A standard office job with fixed hours. Often slightly negative: 'He never wanted a nine-to-five job.'" },
    { w: "to be self-employed", hint: "To work for yourself instead of a company. 'Being self-employed means freedom – and risk.'" },
    { w: "job security", hint: "How safe your job is from being lost. 'Public sector jobs offer more job security.'" },
    { w: "to work remotely", hint: "To work from home or anywhere outside the office. 'Half the team works remotely on Fridays.'" },
    { w: "to meet a deadline", hint: "To finish work on time. 'Journalists live from deadline to deadline.'" },
    { w: "a competitive field", hint: "An area where many people fight for few positions. 'Medicine is a highly competitive field.'" },
    { w: "transferable skills", hint: "Skills useful in any job – teamwork, communication, problem-solving." },
  ] },
  { topic: "Travel & tourism", words: [
    { w: "to broaden the mind", hint: "Travel makes you more open and understanding. 'Travel broadens the mind' is a classic opener – use it with a twist." },
    { w: "mass tourism", hint: "Tourism in huge, damaging numbers. 'Mass tourism is slowly destroying the places it loves.'" },
    { w: "off the beaten track", hint: "Away from the usual tourist routes. 'We found a village completely off the beaten track.'" },
    { w: "a once-in-a-lifetime trip", hint: "A journey you will probably only make once. 'For my grandparents, it was a once-in-a-lifetime trip.'" },
    { w: "to immerse yourself in a culture", hint: "To dive deeply into local life. 'Living with a host family lets you immerse yourself in the culture.'" },
    { w: "eco-tourism", hint: "Travel designed to protect nature and support locals. Useful contrast to mass tourism." },
    { w: "a tourist hotspot", hint: "A place crowded with visitors. 'Hallstatt has become a tourist hotspot.'" },
    { w: "to travel on a budget", hint: "To travel cheaply. 'Interrail is the classic way to travel on a budget.'" },
    { w: "cultural exchange", hint: "Sharing traditions and views between cultures. 'School partnerships create real cultural exchange.'" },
    { w: "to soak up the atmosphere", hint: "To enjoy the feeling of a place. 'We sat in the square and soaked up the atmosphere.'" },
    { w: "overtourism", hint: "When too many tourists overwhelm a place. Modern, precise term for texts about tourism." },
    { w: "a culture shock", hint: "The confusion of meeting a very different culture. 'Moving from a village to Tokyo was a culture shock.'" },
  ] },
  { topic: "Consumerism & money", words: [
    { w: "to live beyond your means", hint: "To spend more than you earn. 'Credit cards make it easy to live beyond your means.'" },
    { w: "an impulse buy", hint: "Something you buy without planning. 'The chocolate at the checkout is a classic impulse buy.'" },
    { w: "to save up for", hint: "To collect money for something specific. 'She is saving up for a year abroad.'" },
    { w: "fast fashion", hint: "Cheap clothing produced quickly and thrown away quickly. A key term for writing on consumption." },
    { w: "a throwaway culture", hint: "A culture of using things once and binning them. Works well paired with fast fashion." },
    { w: "value for money", hint: "Good quality for the price paid. 'The hostel was basic but great value for money.'" },
    { w: "to be in debt", hint: "To owe money. 'Many students leave university deeply in debt.'" },
    { w: "to spend money wisely", hint: "To make sensible spending choices. 'Learning to spend money wisely should be taught at school.'" },
    { w: "a tight budget", hint: "Very little money to work with. 'We planned the trip on a tight budget.'" },
    { w: "conspicuous consumption", hint: "Buying expensive things to show off. Advanced term – use it once, precisely." },
    { w: "to cut back on spending", hint: "To reduce how much you spend. 'Families cut back on spending when prices rise.'" },
    { w: "ethical shopping", hint: "Buying with attention to people and planet. 'Ethical shopping costs more – but who pays otherwise?'" },
  ] },
  { topic: "Society & community", words: [
    { w: "to volunteer for a good cause", hint: "To work unpaid for something worthwhile. 'Thousands volunteer for good causes every weekend.'" },
    { w: "a sense of belonging", hint: "The feeling of being part of a group. 'Clubs give young people a sense of belonging.'" },
    { w: "social inequality", hint: "The unfair gap between rich and poor. 'Education is the best answer to social inequality.'" },
    { w: "to give something back", hint: "To return help to your community. 'After her career, she wanted to give something back.'" },
    { w: "an ageing population", hint: "A society with more and more old people. Standard term in reports and articles on society." },
    { w: "cultural diversity", hint: "The variety of cultures in one place. 'Vienna's cultural diversity is one of its greatest strengths.'" },
    { w: "to bridge the gap", hint: "To reduce the distance between groups. 'Sport can bridge the gap between generations.'" },
    { w: "community spirit", hint: "The feeling of togetherness in a neighbourhood. 'The flood revealed an amazing community spirit.'" },
    { w: "to integrate into society", hint: "To become a full part of a society. 'Language courses help newcomers integrate into society.'" },
    { w: "equal opportunities", hint: "The same chances for everyone. 'Equal opportunities remain a goal, not a reality.'" },
    { w: "a multicultural society", hint: "A society made up of many cultures. Neutral, factual term for reports." },
    { w: "to break down barriers", hint: "To remove obstacles between people. 'Music breaks down barriers that words cannot.'" },
  ] },
  { topic: "AI & the digital future", words: [
    { w: "artificial intelligence (AI)", hint: "Computer systems that perform tasks needing human-like thinking. Write it out once, then use 'AI'." },
    { w: "an AI-generated text", hint: "A text written by a machine. 'Teachers are learning to spot AI-generated texts.'" },
    { w: "a deepfake video", hint: "A fake but realistic video created with AI. 'Deepfake videos make it harder to trust what we see.'" },
    { w: "to automate routine tasks", hint: "To let machines do repetitive work. 'AI automates routine tasks so people can focus on ideas.'" },
    { w: "to be replaced by a machine", hint: "To lose your job or role to technology. 'Not every job can be replaced by a machine.'" },
    { w: "to rely too heavily on AI", hint: "To depend on AI so much that your own skills suffer. 'Students who rely too heavily on AI stop learning.'" },
    { w: "digital literacy", hint: "The ability to use and judge digital tools sensibly. 'Digital literacy is as basic as reading now.'" },
    { w: "to regulate new technologies", hint: "To set legal rules for technology. 'The EU was the first to regulate new technologies like AI.'" },
    { w: "an algorithm", hint: "The set of rules a computer follows to decide something. 'An algorithm decides what you see next.'" },
    { w: "human oversight", hint: "Humans checking and controlling what machines do. 'Every AI system needs human oversight.'" },
    { w: "to raise ethical concerns", hint: "To create questions about right and wrong. 'Facial recognition raises serious ethical concerns.'" },
    { w: "to adapt to technological change", hint: "To adjust to a world changed by technology. 'Schools must adapt to technological change, not ignore it.'" },
  ] },
  { topic: "Media & news", words: [
    { w: "to keep up with the news", hint: "To stay informed about current events. 'Most teenagers keep up with the news on their phones.'" },
    { w: "a reliable source", hint: "A source you can trust. 'Check whether the claim comes from a reliable source.'" },
    { w: "to spread disinformation", hint: "To distribute deliberately false information. Stronger and more precise than 'fake news'." },
    { w: "media literacy", hint: "The ability to understand and question media. 'Media literacy should be a school subject of its own.'" },
    { w: "a paywall", hint: "A barrier that makes you pay to read articles. 'More and more quality journalism sits behind a paywall.'" },
    { w: "public service broadcasting", hint: "Radio and TV financed by the public, like the ORF or the BBC. Useful in writing on trustworthy news." },
    { w: "investigative journalism", hint: "Journalism that uncovers hidden facts. 'Investigative journalism brought the scandal to light.'" },
    { w: "a news outlet", hint: "A company that publishes news – paper, site or channel. 'Compare how two news outlets report the same story.'" },
    { w: "to fact-check a claim", hint: "To check whether a statement is true. 'Fact-check a claim before you share it.'" },
    { w: "clickbait headlines", hint: "Headlines designed only to make you click. 'Clickbait headlines promise more than the article delivers.'" },
    { w: "freedom of the press", hint: "The right of media to report without state control. 'Democracy dies without freedom of the press.'" },
    { w: "to quote somebody out of context", hint: "To repeat words in a misleading way. 'The minister claimed she had been quoted out of context.'" },
  ] },
  { topic: "Migration & global citizenship", words: [
    { w: "to flee a war zone", hint: "To escape from an area at war. 'Millions have fled war zones in recent years.'" },
    { w: "to seek asylum", hint: "To officially ask another country for protection. 'The family sought asylum in Austria.'" },
    { w: "a refugee camp", hint: "A temporary settlement for people who have fled. 'She spent two years in a refugee camp before moving on.'" },
    { w: "to integrate into a new society", hint: "To become part of a new country's life. 'Work and language are the keys to integrating into a new society.'" },
    { w: "a residence permit", hint: "The official document allowing you to live in a country. 'Without a residence permit, nothing else is possible.'" },
    { w: "to face discrimination", hint: "To be treated unfairly because of who you are. 'Many newcomers face discrimination when looking for flats.'" },
    { w: "a sense of global responsibility", hint: "The feeling that world problems concern us all. 'Climate change demands a sense of global responsibility.'" },
    { w: "to overcome a language barrier", hint: "To manage communication despite different languages. 'Children overcome language barriers astonishingly fast.'" },
    { w: "a skilled worker", hint: "Someone with valuable professional training. 'Austria actively recruits skilled workers from abroad.'" },
    { w: "cultural identity", hint: "The feeling of belonging to a particular culture. 'You can build a new life without giving up your cultural identity.'" },
    { w: "to build a new life", hint: "To start again in a new place. 'They arrived with two suitcases and built a new life.'" },
    { w: "humanitarian aid", hint: "Emergency help – food, shelter, medicine. 'Humanitarian aid reaches the camps by convoy.'" },
  ] },
];

